### ISSUE TITLE
You can Yaz0 compress a .BFRES

### ISSUE THREAD

**Issue by roket333** [KillzXGaming/Switch-Toolbox#100]
If you Yaz0 compress a BFRES, it will stay as a BFRES yet act like an SBFRES, it doesn't really make much sense to be able to do this

**Comment by GRAnimated** [comment]
Some games like BOTW use .sbfres which is a Yaz0 compressed BFRES.

**Comment by KillzXGaming** [comment]
If the file format opened was compressed by default, it will always ask to compress back or not. Also not every game uses sbfres or szs for compressed bfres, some games may not touch the extension, so it's best to not automate that.
