### ISSUE TITLE
The ability to clear the workspace

### ISSUE THREAD

**Issue by zrksyd** [KillzXGaming/Switch-Toolbox#101]
It gets a bit annoying having to restart the program to clear the workspace.

**Comment by KillzXGaming** [comment]
There's multiple ways to clear it. You can close the window you are currently on, or close all of them (Windows - Close All). If you are using 0.8, that build is extremely old and lacks alot of features.

**Comment by KillzXGaming** [comment]
I also now added fixes for removing individual files from an existing editor. So clearing stuff should be perfectly fine. I'll close this for now, but if there's something I'm not quite getting you can reopen it.
