### ISSUE TITLE
Unable to view models from BMD files.

### ISSUE THREAD

**Issue by Bri1101** [KillzXGaming/Switch-Toolbox#105]
I heard earlier when the tool added BMD support a few days ago, but for some reason Switch Toolbox throws this error at me when I attempt to view the model:
![unknown](https://user-images.githubusercontent.com/30452039/62484543-69349600-b788-11e9-9997-f262085de823.PNG)

**Comment by KillzXGaming** [comment]
Could you send a sample file?

**Comment by Bri1101** [comment]
[sample.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/3472963/sample.zip)

**Comment by KillzXGaming** [comment]
Thanks fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/a80f6c31b5617e3b304e5e162acc213f9e1b4741
