### ISSUE TITLE
Saving 3ds .ptcl files

### ISSUE THREAD

**Issue by VelouriasMoon** [KillzXGaming/Switch-Toolbox#108]
When saving a .ptcl from a 3ds game(In this case FE Fates and FE Shadows of Valentia) it switches some data to Big Endian when it should be Little Endian.

**Comment by KillzXGaming** [comment]
Can you test it on the latest commit and check if the file works in game?

**Comment by VelouriasMoon** [comment]
Seems to be working fine, data all looks right and the file works in game. If any issue do come up down the road I'll be sure to inform you
