### ISSUE TITLE
The ability to batch convert DDS to BNTX

### ISSUE THREAD

**Issue by zrksyd** [KillzXGaming/Switch-Toolbox#109]
Either a way to open a folder of DDS's and convert each into BNTX or a way to use Switch Toolbox via the command prompt.

**Comment by KillzXGaming** [comment]
While cmd options is planned at some point, I added in a an option in the File menu. Just select all the DDS files you want to batch as a bntx. https://github.com/KillzXGaming/Switch-Toolbox/commit/751c1dc550de90820b673bb669b067493bb7cb39
