### ISSUE TITLE
Mario Tennis Aces character UV's aren't scaled properly

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [KillzXGaming/Switch-Toolbox#110]
![image](https://user-images.githubusercontent.com/33284629/63014951-a2a38a80-be87-11e9-9211-3f9010123667.png)
The UV's are half the size they should be on the U axis in some cases.

**Comment by KillzXGaming** [comment]
Might rely on the texsrt0 shader params, though i never apply those due to how varied the uses are (some games will use weird values and i don't exactly know when they are used and how)

**Comment by KillzXGaming** [comment]
These should display correctly
