### ISSUE TITLE
no skeleton found to assign

### ISSUE THREAD

**Issue by YoshiCrystal** [KillzXGaming/Switch-Toolbox#113]
When I try to export an animation as .smd, the program says that there's no skeleton found to assign, how do I assign the animation to a model so I can export it?

**Comment by en-kig** [comment]
How did you solve this?

**Comment by theonerm2** [comment]
> How did you solve this?

I solved it by exporting them all as bfska and importing them to a model. So for example go to PlayerAnimation. Go to the skeletal animations. Export all as bfska. Then import into Mario animations folder. Then export all those as smd. That's what worked for me.
