### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by zrksyd** [KillzXGaming/Switch-Toolbox#114]
I keep instinctively doing stuff like Ctrl + O to open. Here are my suggestions for some shortcuts:
Ctrl + O = Open
Ctrl + S = Save
Ctrl + Alt + S = Save as
Ctrl + W = Close
I think keyboard shortcuts would also be useful in the right-click context menu when selecting a texture or something to export or replace or whatnot.

**Comment by KillzXGaming** [comment]
Alright all those are added https://github.com/KillzXGaming/Switch-Toolbox/commit/655cdff1429c755a9b3460a512670bcd58027a82 and https://github.com/KillzXGaming/Switch-Toolbox/commit/de84563377201677ea032ee658322da471edf02f. I'm not %100 sure if any older formats are missing shortcuts, but most should use them and function properly.
