### ISSUE TITLE
CameraAnims are not serialized properly

### ISSUE THREAD

**Issue by OatmealDome** [KillzXGaming/Switch-Toolbox#12]
Serializing a ResFile with a CameraAnim causes the application to crash in `nn::g3d::ResCameraAnim::Initialize`, as the provided `nn::g3d::CameraAnimResult` pointer is invalid. 

In addition, ResFile.PreSave() does not add any of the CameraAnims, LightAnims, FogAnims, or UserData to their respective ResDicts in SceneAnim. However, this does not appear to cause the above issue?

(How exactly do you approach a serialization issue when trying to debug it...? There isn't really a 'proper' debugger on the Switch as of right now, so I'm not sure where to even start troubleshooting.)

**Comment by KillzXGaming** [comment]
This should now be fine for the newest library.
