### ISSUE TITLE
Mario Tennis Aces Armature Hair Issues

### ISSUE THREAD

**Issue by ninetalescommander** [KillzXGaming/Switch-Toolbox#120]
It doesn't happen with all characters but for some reason, when I export certain characters like Waluigi, the armatures for the hair are not properly connecting to the appropriate meshes.
I don't know if it's because I'm exporting as DAE but either way it's making it really awkward to properly assign the correct armatures to the vertices.
Any idea how to fix this?

**Comment by ninetalescommander** [comment]
Update: Upon looking more into it, it seems like when the DAE is exporting, some of the armature is straight up getting "disconnected". Here's a screenshot comparison to show what I mean.
![9af855ee0b6f9ae041c66e94231e0803](https://user-images.githubusercontent.com/53667865/63780519-26c22d00-c8e0-11e9-92e8-9aa3dc18705b.png)
![9760e54546ffe04538b82feb49fb3606](https://user-images.githubusercontent.com/53667865/63780520-26c22d00-c8e0-11e9-937b-48a308d57a9b.png)

**Comment by KillzXGaming** [comment]
This is fixed I believe but feel free to reopen if it's not.
