### ISSUE TITLE
Open gfbanm files

### ISSUE THREAD

**Issue by Manurocker95** [KillzXGaming/Switch-Toolbox#121]
I can export them, but not see them nor use them anyway. In the text editor, it just says EOT

**Comment by KillzXGaming** [comment]
The tool only supports gfmdl, bnsh, and bntx. I don't plan to do every file in the gfpak, but animations are planned

**Comment by lumciaro** [comment]
Hey, any progress on gfbanm support?

**Comment by KillzXGaming** [comment]
Yeah it's almost fully supported. I still need to figure out rotations and i am currently working on gfbmdl editing.

**Comment by lumciaro** [comment]
Nice!

**Comment by lumciaro** [comment]
Hey, it's been an entire month since you said that it's almost fully supported, how's the progress?

**Comment by KillzXGaming** [comment]
At the time I was also finishing up gfbmdl but that's pretty much functional. I haven't really gotten around to finishing gfbanm, and researching is kinda annoying atm since my switch has been giving issues. I'll be sure to close this once they are working.

**Comment by tillfox** [comment]
Hi! is there any progress on gfbanm support?

**Comment by maierfelix** [comment]
Can this be reopened? The animations in LGPE aren't correctly displayed yet @KillzXGaming

**Comment by KillzXGaming** [comment]
You can make a new issue since it's specific to LGPE. That game handles rotations differently and is currently unknown how.

**Comment by hYdos** [comment]
Where did you learn about this format? It's very compact compared to glb and smd and looking to use it myself.
