### ISSUE TITLE
NS Mii Maker Version 9 BFRES

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [KillzXGaming/Switch-Toolbox#122]
The files open however there is an error.
![image](https://user-images.githubusercontent.com/33284629/64907541-d9212f00-d6eb-11e9-8456-8635bfb81834.png)
Not sure what else to say.

**Comment by KillzXGaming** [comment]
Are you sure you opened a bfres? That seems to be an error loading a bfsha?

**Comment by CosmicDreamsOfCode** [comment]
Double clicking on a BFRES caused the error to show the first time I did it.
Maybe it's because double clicking a file in toolbox causes it to also click on the file below the one you are opening sometimes.

**Comment by KillzXGaming** [comment]
Should work now from https://github.com/KillzXGaming/Switch-Toolbox/commit/b1c37cab72e025c0135e0b0bf5c1b747f7dec877
