### ISSUE TITLE
Splatoon 1/2 Stage Scene Animations not exporting

### ISSUE THREAD

**Issue by AriIsADumb** [KillzXGaming/Switch-Toolbox#124]
Trying to export the Camera for a Sceme Animation causes nothing to happen.
Trying to export the Animation file itself results in the following error:
'InvalidArgument=Value of '0' is not valid for 'SelectedIndex'. Parameter name: SelectedIndex.'
In addition to this, Toolbox recognises these files as folders, and upon trying to export the camera, the only option is 'All Files'.
EDIT:
Sorry if I word things really badly, haha
Using Mahi Mahi's as an example, when I say 'Animation file itself', I'm referring to what is 'StageInDemo_A', and when I say 'Camera for a Scene', I'm referring to what is 'StageInDemo_ACamera'
Just wanted to clear up any potential confusion.
EDIT 2:
Here's an image of what the directory looks like.
![screenshot](https://user-images.githubusercontent.com/52177507/64911917-c6c0e880-d71f-11e9-9972-c48ae212460a.png)

**Comment by KillzXGaming** [comment]
This is fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/368781f2aae45f7b5ee49ae04e7076541a14e06d
