### ISSUE TITLE
GraphicsPreset.szs from Super Mario Odyssey does not open

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [KillzXGaming/Switch-Toolbox#127]
The file also does not work with sarc_tool. It seems to be a slight bit different from other files.

**Comment by KillzXGaming** [comment]
What do you mean cannot open?
![image](https://user-images.githubusercontent.com/13475262/65288259-2d754600-db14-11e9-9b9d-b0a607ed5f50.png)

**Comment by CosmicDreamsOfCode** [comment]
Toolbox doesn't display an error or anything like that, it just kinda doesn't open the file at all.
SARC tool extracts the file but it doesn't actually dump any of the files inside it.

If it makes any difference my SMO dump is from the latest game version.

**Comment by CosmicDreamsOfCode** [comment]
![image](https://user-images.githubusercontent.com/33284629/65323039-40cdf300-dba0-11e9-92b7-108207d81574.png)
Ok im at least getting an error now.

**Comment by KillzXGaming** [comment]
Can you show the file in hex? It's pretty common update files decrypt wrong and have corrupted data.

**Comment by CosmicDreamsOfCode** [comment]
Will do soon.

**Comment by CosmicDreamsOfCode** [comment]
![image](https://user-images.githubusercontent.com/33284629/65343423-db442b80-dbcc-11e9-9bbd-1fa0558e6ab0.png)

**Comment by MelonSpeedruns** [comment]
Opens perfectly fine for me as well....

**Comment by CosmicDreamsOfCode** [comment]
[GraphicsPreset.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/3637655/GraphicsPreset.zip)
Here's the file.

**Comment by KillzXGaming** [comment]
That is pretty strange. Despite the base game one working fine, the update one gives character issues with some of the Japanese text used for the files.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/43dc09c39cb898136356c5b41785319d3f58771e
