### ISSUE TITLE
Link's Awakening MSBT Crash

### ISSUE THREAD

**Issue by wowjinxy** [KillzXGaming/Switch-Toolbox#128]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt16()
   at FirstPlugin.MSBT.TXT2.ReadMessageString(FileReader reader, UInt32 index) in C:\projects\switch-toolbox\File_Format_Library\FileFormats\Message\MSBT.cs:line 288
   at FirstPlugin.MSBT.TXT2.Read(FileReader reader, Header header) in C:\projects\switch-toolbox\File_Format_Library\FileFormats\Message\MSBT.cs:line 271
   at FirstPlugin.MSBT.Header.Read(FileReader reader) in C:\projects\switch-toolbox\File_Format_Library\FileFormats\Message\MSBT.cs:line 134
   at Toolbox.Library.IO.STFileLoader.SetFileFormat(IFileFormat fileFormat, String FileName, Stream stream, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat FileCompression)
   at Toolbox.Library.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, Int64 DecompressedSize, Int64 CompressedSize)
   at Toolbox.Library.IO.STFileLoader.OpenFileFormat(String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, UInt32 DecompressedSize, UInt32 CompressedSize)
   at Toolbox.MainForm.OpenFile(String FileName, Boolean InActiveEditor) in C:\projects\switch-toolbox\Toolbox\MainForm.cs:line 283
   at Toolbox.MainForm.OpenFileSelect() in C:\projects\switch-toolbox\Toolbox\MainForm.cs:line 256
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

Toolbox
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Toolbox.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

Toolbox.Library
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Toolbox.Library.DLL

Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

DirectXTexNetImpl
    Assembly Version: 1.0.0.3
    Win32 Version: 
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/x64/DirectXTexNetImpl.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll

OpenTK
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/OpenTK.dll

Octokit
    Assembly Version: 0.31.0.0
    Win32 Version: 0.31.0.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Octokit.DLL

System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll

SFGraphics
    Assembly Version: 1.0.6956.42501
    Win32 Version: 1.0.6956.42501
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/SFGraphics.dll

OpenTK.GLControl
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/OpenTK.GLControl.dll

Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll

FirstPlugin.Plg
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/Plugins/FirstPlugin.Plg.dll

GL_EditorFramework
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/GL_EditorFramework.DLL

Syroot.Maths
    Assembly Version: 1.5.3.0
    Win32 Version: 1.5.3.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/Syroot.Maths.dll

WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/Plugins/WeifenLuo.WinFormsUI.Docking.DLL

Syroot.NintenTools.NSW.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/Syroot.NintenTools.NSW.Bfres.dll

Syroot.NintenTools.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/Syroot.NintenTools.Bfres.dll

BcresLibrary
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/Plugins/BcresLibrary.DLL

Syroot.NintenTools.NSW.Bntx
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/Syroot.NintenTools.NSW.Bntx.dll

Syroot.BinaryData
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/Syroot.BinaryData.dll

Syroot.NintenTools.MarioKart8
    Assembly Version: 0.5.2.0
    Win32 Version: 0.5.2.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/Syroot.NintenTools.MarioKart8.dll

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

DirectXTexNet
    Assembly Version: 1.0.0.3
    Win32 Version: 1.0.0.3
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/DirectXTexNet.DLL

SARCExt
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/SARCExt.dll

Be.Windows.Forms.HexBox
    Assembly Version: 1.6.0.38064
    Win32 Version: 1.6.0.38064
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/Be.Windows.Forms.HexBox.dll

Cyotek.Windows.Forms.ImageBox
    Assembly Version: 1.2.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/Cyotek.Windows.Forms.ImageBox.dll

WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///D:/Launchbox/Tools/Switch-Toolbox/Lib/Plugins/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL

System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by shibbo** [comment]
Looks like they changed the MSBT format for this game.

**Comment by CosmicDreamsOfCode** [comment]
Is the game not running on Unreal Engine? seems odd they'd use MSBT along side it if they do.

**Comment by wowjinxy** [comment]
Nope, it's proprietary

**Comment by Kysonati** [comment]
Try MSBT Editor Reloaded

**Comment by CosmicDreamsOfCode** [comment]
Oh, interesting. Still using BFRES and the like i assume?

**Comment by wowjinxy** [comment]
Yes

**Comment by wowjinxy** [comment]
MSBT Editor Reloaded opens it, but says it's blank, time to try Kuriimu.

**Comment by wowjinxy** [comment]
Kuriimu works just fine

**Comment by KillzXGaming** [comment]
Should work now
