### ISSUE TITLE
Please fix the bfres save atm

### ISSUE THREAD

**Issue by vgisuruex** [KillzXGaming/Switch-Toolbox#13]
smash forge's bfres atm is broken too so please i need this

**Comment by KillzXGaming** [comment]
What bfres? What game? The latest release should be fine for most games, however Splatoon has many that crash and if you edit one with textures that are in a separate file, it may break.

**Comment by vgisuruex** [comment]
When i import a model to a bres file and save it and opemln it up the model is not the imported one but the original one

**Comment by KillzXGaming** [comment]
Wii U bfres isn't fully supported yet. Will next update however!

**Comment by vgisuruex** [comment]
if so could you build it and put it in the releases as soon as it updates?

**Comment by KillzXGaming** [comment]
Should be fixed now for wii u
