### ISSUE TITLE
0.9 Bfres fail to load if using multiple shape animations (invalid header size)

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [KillzXGaming/Switch-Toolbox#130]
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Syroot.NintenTools.NSW.Bfres.ResException: Invalid signature, expected 'FSHA' but got 'HA`

[ObjKoton.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/3635657/ObjKoton.zip)

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/a93b28c75637c9fa9c5f03d9915dc5311869719d
