### ISSUE TITLE
.szs in Wii U .pack files not saving properly

### ISSUE THREAD

**Issue by DiamC23** [KillzXGaming/Switch-Toolbox#133]
Messes up textures (or UVs, not sure) and animations (if it has animations the model ends up invisible in my experience). Everything looks fine in toolbox preview, not in game. I've only had this in Splatoon, haven't checked any other games.

Edit: This only happens with .pack files too, saving any other szs works fine. Trying to export the szs, edit and save it, then import it back into the pack still causes it to look wrong. Sorry for any weird wording.

Example of broken saving and how its supposed to look
![Broken](https://user-images.githubusercontent.com/55969422/65849711-8e650100-e300-11e9-98dd-443d8fb34375.png)
![normal](https://user-images.githubusercontent.com/55969422/65849742-afc5ed00-e300-11e9-8838-007d60df83c6.png)

**Comment by KillzXGaming** [comment]
What did you edit in particular? Splatoon is extremely picky due to shaders so it makes editing them difficult. Certain things like attributes, skin count, etc need to be kept the same when editing (which can be enabled in the inject tab in the import settings).

**Comment by DiamC23** [comment]
The example here is with content\Pack\Weapon.Pack\Wmn_Shot_Normal.szs, but it also happens with other .packs with .szs (like Player.pack and Enemy.pack). 

Even opening the .pack, then opening the .szs and saving messes up the textures and animations without modifying anything inside it.

Other .szs work fine, if they’re not in a .pack (for example, content\Model\Wmn_Shot_Normal_REF.szs can be edited fine)

**Comment by KillzXGaming** [comment]
I believe this is fixed now, though feel free to reopen if it isn't.
