### ISSUE TITLE
Bugfix: TPL Palette 10

### ISSUE THREAD

**Issue by NWPlayer123** [KillzXGaming/Switch-Toolbox#137]
I managed to find a format 10 file, it's a leftover/unused one in Spectrobes: Origins for Wii.
[card_input_circuit.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/3727067/card_input_circuit.zip)
Figured you'd want to add support.
![Screenshot_173](https://user-images.githubusercontent.com/3280345/66793629-8342d100-eebb-11e9-8e40-8f48a2e74252.png)

**Comment by KillzXGaming** [comment]
This should fix it. https://github.com/KillzXGaming/Switch-Toolbox/commit/2df06f463deed11cd62a7d47a5e435e145078a50
