### ISSUE TITLE
Error when opening textures

### ISSUE THREAD

**Issue by MegaSuperab** [KillzXGaming/Switch-Toolbox#138]
I've attempted to open both nutexb and bntx files using the latest release and doing so brings up the error "Unable to cast object of type 'System.Windows.Forms.ToolStripProfessionalRenderer' to type 'Toolbox.Library.Forms.MenuRenderer'." More information can be given if needed.

**Comment by KillzXGaming** [comment]
Could you show the error log in a paste bin or something? I can't replicate it, might need to add the 
 latest release of the tool to a clean folder and try loading from that.

**Comment by MegaSuperab** [comment]
Here you go. https://gist.github.com/MegaSuperab/d3c29105abb9a4391ce9c00531fe7a92

**Comment by KillzXGaming** [comment]
Ah alright it was an issue with white theme, should be fixed now with https://github.com/KillzXGaming/Switch-Toolbox/commit/6eabbda19b856fb8fcb333167298905fee35dc6f
