### ISSUE TITLE
BYAML - invalid string encoding

### ISSUE THREAD

**Issue by SuperHackio** [KillzXGaming/Switch-Toolbox#139]
## Issue Details
The toolbox uses one encoding type for all BYAML files
However,not all BYAML files use the dame encoding, as some strings are encoded as **SHIFT-JIS**
Example: StageList.byml (SM3DW) (I sent it before if you remember that)

You can fix reading the strings by finding the part in the `byamlfile.LoadN()` function that reads the strings. By default iirc the encoding is UTF-8.

### Why this is an issue
Saving any BYAML file that had Japanese in it will save as the incorrect UTF-8 string encoding, which breaks files with Japanese in them.
***
I hope that this issue can be fixed without too many hardships to the overall functionality of the toolbox. If you have any questions let me know.

**Comment by KillzXGaming** [comment]
Fixed using the shift JIS setting in the byaml editor https://github.com/KillzXGaming/Switch-Toolbox/commit/c922ff1e4ffd675486ceeabf4dda197c5fcc6d34
