### ISSUE TITLE
DirectXTexNetImpl.dll error on boot. App opens but crashes when texture is loaded, even though file is present.

### ISSUE THREAD

**Issue by NickHam13** [KillzXGaming/Switch-Toolbox#142]
I get the FileNotFoundException DirectXTexNetImpl.dll error on boot. The tool still boots anyway, but whenever I open a texture it just freezes for about 3 seconds and then shuts mysteriously closes without a trace. I've checked and the file is in the .zip. I've already unblocked the .zip archive before extracting it but that didn't change anything. DirectX is installed directly from Microsoft, even rebooted and it still didn't fix the issue. I just wanna convert images to xtx.z format for SNES Online games.

**Comment by KillzXGaming** [comment]
Make sure [this](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) is installed.

**Comment by NickHam13** [comment]
Installed it and rebooted, still get the same error.

**Comment by KillzXGaming** [comment]
Rebooted your PC? Also is this on the latest experimental build?

**Comment by NickHam13** [comment]
Yeah, as in I entered the start menu and restarted. Using the experimental build updated through the updater.

**Comment by KillzXGaming** [comment]
What version of windows is it on and is it x86 or x64 bit?

**Comment by NickHam13** [comment]
Latest update of Windows 10, x86.

**Comment by KillzXGaming** [comment]
Oh i see, so 32 bit PCs have issues. Can you try deleting the x64 folder? I recall hearing that fixed some issues before.

**Comment by NickHam13** [comment]
Turns out I'm an idiot and actually have an x64 processor. Anyway, deleting the x64 folder still got rid of the error and I can now view and edit textures. Thanks for the help.
