### ISSUE TITLE
34 errors during compile, files access restricted

### ISSUE THREAD

**Issue by Official-MadoX** [KillzXGaming/Switch-Toolbox#145]
I'm pretty sure this isn't a common issue but..
![image](https://user-images.githubusercontent.com/39462203/68812387-7fc87400-0638-11ea-8c30-2d0e0927cea1.png)
I compiled as Release

**Comment by KillzXGaming** [comment]
You can understand the issue a bit [here](https://stackoverflow.com/questions/51348919/couldnt-process-file-resx-due-to-its-being-in-the-internet-or-restricted-zone-o). Try right clicking the zip of the source code, and check "unblock". Then re extract

**Comment by Official-MadoX** [comment]
yeah, dumb me, i just figured out, thanks!
