### ISSUE TITLE
Improved DAE Exporter?

### ISSUE THREAD

**Issue by ninetalescommander** [KillzXGaming/Switch-Toolbox#146]
At first I was excited when I saw the update for the DAE Exporter but after playing around with it in Blender, I genuinely am finding it hard to see how this is better. Here's the issues I've found so far

- Secondary UV Maps are not exported anymore, this is a major issue as many models rely on a 2nd UV Map for specific overlays like eye pupils
- For some reason, all vertex groups are now put into 1 mesh. I'm currently looking through the model for Waluigi in Mario Tennis Aces and literally all vertex groups are in every mesh
- In addition, bones are no longer working as intended. Beforehand the worst I'd get is certain bones not doing anything with all the others working as intended but now even standard bones like spines are moving vertexes it shouldn't.

On the bright side, I was able to spot some good points. The mesh names now import properly which is a good improvement and this time all bones, including the root bones, are properly included but sadly that's where my good points end.
At the very least, I think the previous DAE exporter should be brought back alongside this 1 as that, at least for me, was better than this 1.

**Comment by KillzXGaming** [comment]
All the issues are hopefully fixed now so if you could confirm that'd be great. It's a totally new writer so some things are bound to break, although I've had tested quite a few with no issues. The old exporter is also a setting now just incase something gives issues.
