### ISSUE TITLE
Luigi's Mansion 3 exporting error

### ISSUE THREAD

**Issue by Cyrobyte** [KillzXGaming/Switch-Toolbox#147]
Trying to export a .dict file I get this error, I am using the latest version of Switch Toolbox 
![error](https://user-images.githubusercontent.com/57842745/68998669-84cd3380-0883-11ea-977b-deb0a1889ce3.PNG)

**Comment by KillzXGaming** [comment]
Which file did you export? Was it in an .nsp file?

**Comment by Cyrobyte** [comment]
.nsp

**Comment by KillzXGaming** [comment]
Oh i see so i suppose it happens if it's double clicked on? It uses the file path to find .data so it won't be able to load them unless extracted, but i could have it search the archive aswell.

**Comment by Cyrobyte** [comment]
Yes I double click the .dict and then right click to save then that error above occurs.

**Comment by Cyrobyte** [comment]
Even when I extract the folder that the models are in it works, However when I open the .dict and extract the model it's folder I receive this error 
![Error 2](https://user-images.githubusercontent.com/57842745/68999219-a2060000-088b-11ea-8322-694bb9cfa5c7.PNG)

**Comment by KillzXGaming** [comment]
Should be fixed now. I don't have an nsp on me to check exactly so let me know if it works.

**Comment by Cyrobyte** [comment]
It worked! Thank you! I still have to convert the whole folder for it to work but thanks again!

**Comment by KillzXGaming** [comment]
Alright model exporting is also fixed from folders and also now exports separate in dae files. (It only loads when clicked on so i forgot to have it update on export).
