### ISSUE TITLE
{request} Ability to either Delete bntx or build gfpak

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [KillzXGaming/Switch-Toolbox#149]
1 ) the ability to delete .bntx from inside gfpak to redeuce mod size and only add what is changed
2} the ability to make a new gfpak 

![image](https://user-images.githubusercontent.com/18043258/69023873-bc78d000-0996-11ea-90f7-35eba0bb7af6.png)

**Comment by wowjinxy** [comment]
I'd like to second this, mainly rebuilding
