### ISSUE TITLE
Inverted texture textures

### ISSUE THREAD

**Issue by Bri1101** [KillzXGaming/Switch-Toolbox#154]
I've been going between character models and it seems like the character's face's color is inverted, but the texture itself are normal and not inverted.
![Capture](https://user-images.githubusercontent.com/30452039/69503728-d9f3ef80-0eea-11ea-94f6-4e98a1a888af.PNG)
.
Edit: It seems like it's doing the same thing for some of the other models in Switch Toolbox.

**Comment by KillzXGaming** [comment]
Should be fixed now https://github.com/KillzXGaming/Switch-Toolbox/commit/1c787477d1b7b2e5a3f758c716dcbd058453f7c1
