### ISSUE TITLE
"Reset Default Settings"

### ISSUE THREAD

**Issue by BruhLookAtThis** [KillzXGaming/Switch-Toolbox#156]
Just want an option to reset Toolbox settings to default.

Got caught up just clicking buttons in the settings and forgot what i changed. Would like a way to fresh start, undoing my f**kups

**Comment by KillzXGaming** [comment]
Added https://github.com/KillzXGaming/Switch-Toolbox/commit/880ab08e79752e2847b3708a8407d8874619a0ef
