### ISSUE TITLE
Add mass import/replace

### ISSUE THREAD

**Issue by exalented** [KillzXGaming/Switch-Toolbox#157]
I'm searching for a tool that can replace textures into their corresponding bntx's at a large scale. Preferably a command line option.
Is this feature planned?
![image](https://user-images.githubusercontent.com/9328864/70140883-974cb880-164a-11ea-8f58-1ebef6e425be.png)

**Comment by KillzXGaming** [comment]
![Untitled](https://user-images.githubusercontent.com/13475262/70872085-5a01f800-1f73-11ea-9764-eb8b0e53f203.png)

Latest has a way to batch replace textures given the names are matched located in the quick access folder. I do plan to add gfpak editing by CLI in a separate tool for batch editing multiple easily.
