### ISSUE TITLE
.gfpak Value Params transformations are not applied when exporting the model

### ISSUE THREAD

**Issue by Voileexperiments** [KillzXGaming/Switch-Toolbox#158]
I'm exporting some `.gfbmdl` models out of `.gfpak` files from existing games, and for some reasons some textures get their UV mapping messed up when exported to `.dae` (the UV map in intact but the transformation is clearly wrong). So I looked carefully and found that the materials with bad UVmaps have `ColorUVScaleU 2` in their Value Params while the ones that are fine has `ColorUVScaleU 1`. What do these `ColorUVSomething` values *mean* anyway? I can probably guess the correct transformation after some jiggling with the exported models but also maybe not (besides I haven't checked the other models, they might have different Value Params), so knowing it would be helpful. 

Also, the UV editor never worked for me for some reasons. The two dropdowns at the bottom are always empty:

![image](https://user-images.githubusercontent.com/14909989/70145426-05d95700-16db-11ea-87a2-8d9eae887551.png)

**Comment by KillzXGaming** [comment]
UV editor will be fixed in a new update which is now using a new 2D renderer. 
Textures for gfbmdl use  ColorUVScaleU  and ColorUVScaleV to scale the UVs for the color/diffuse map on the X/Y axis.

![Capture](https://user-images.githubusercontent.com/13475262/70187139-7ff9e380-16bb-11ea-9db2-f62b6c846040.PNG)

I cannot unfortunately export these as DAE afaik that would work in other 3D programs as it's per texture map. Like these normal maps.

![Capture2](https://user-images.githubusercontent.com/13475262/70187242-b46d9f80-16bb-11ea-90c9-38c084e6a4d0.PNG)

**Comment by Voileexperiments** [comment]
> I cannot unfortunately export these as DAE afaik that would work in other 3D programs as it's per texture map. Like these normal maps.

The problem is that UV coordinate wrapping behaviour is entirely implementation-dependent. Depending on the program it can do these things:

- Truncate to inside boundary
- Ping-pong across boundary
- Clamped to `[0,1]`
- All of the above
- Gives up and crashes

So it's desired to export the model with a well-behaved UV mapping, or at least it should be well-documented; it took me a while to figure out texture coordinates are truncated in the V direction but does ping-pong looping in U direction. After knowing that fixing the UV map manually was not hard but it's obscure and confusing, and I do prefer if the export process fixes it so I don't have to do the same for like a hundred models.

**Comment by KillzXGaming** [comment]
It's not really feasible with DAE and certain programs like blender afaik. It lacks proper wrap modes (which is set in the DAE materials) and also proper per texture transforms. If i were to transform them by the color map all the other maps would break.

**Comment by Voileexperiments** [comment]
Okay, but in the worst case the behaviour should probably be documented somewhere. It was not mentioned anywhere and it certainly took me a while to figure out the actual transformation.

**Comment by KillzXGaming** [comment]
It makes alot more sense with the new UI that will be updated soon. If there's a wiki for the game's formats I can add info on how the parameters work.

**Comment by KillzXGaming** [comment]
These now have a setting to export as transformed so this should be fixed.
