### ISSUE TITLE
Untick/Tick Multiple Bones?

### ISSUE THREAD

**Issue by ninetalescommander** [KillzXGaming/Switch-Toolbox#159]
Right now we have to tick all bones on a chain 1 by 1 which is honestly annoying. Can you add in an option so all bones on 1 "Bone Chain" can be ticked/un-ticked?

**Comment by KillzXGaming** [comment]
That should already be functional, just hold down shift and check the bone. I don't do it automatically incase the user may want to hide only specific ones.
