### ISSUE TITLE
Replace From Folder doesn’t recalculate mip levels for BotW textures

### ISSUE THREAD

**Issue by GingerAvalanche** [KillzXGaming/Switch-Toolbox#160]
Individual Replace recalculates mip levels just fine, but when there’s 45+ textures in a bfres, that gets tiresome.

Steps to reproduce:
-open a tex1
-export all textures to folder
-edit a texture to resize it, reduce by half (any/all textures, doesn’t matter)
-Replace From Folder
-in the import settings dialog, it will default to the original number of mip levels, not the new number
—if you import them (even after changing the mip levels to the proper number) then trying to view any of the mip levels for that texture other than 0 will cause an exception.

A workaround for this, other than replacing all textures individually, is:
-make sure a tex1 and tex2 are both in your working directory
-delete all textures except one from the tex1
-replace that texture with the updated one
-save the tex1
-generate the tex2, overwriting the original
-restart toolbox, opening the tex1 again
-import all other textures (other than the one you replaced 3 steps ago)

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/56eecea8d317e7854a1ec6faec41c8b1c0c4580b
