### ISSUE TITLE
"Could not find a part of the path" error with .gfbmdl files

### ISSUE THREAD

**Issue by LukasBrauschHFU** [KillzXGaming/Switch-Toolbox#161]
On the newest version of this program, when I import a .dae to replace a .gfbmdl and then try to safe, the program gives me an error that states:  "Could not find a part of the path ". 
In the details it tells me that a part called "gfmdl.fbs" is missing: 
"System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\Desktop\toolbox\flatbuffers\gfbmdl.fbs'" 

Edit: 
I found a workaround for this error: 

Download this rep and move the "FlatBuffers" folder from "Switch-Toolbox-master\Switch_Toolbox_Library\Resources" into the folder where your Switch-Toolbox.exe file is.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/217f53a1489482fefabf4795dcc1250f619c5051
