### ISSUE TITLE
Japanese/UTF-8 User data breaks

### ISSUE THREAD

**Issue by VelouriasMoon** [KillzXGaming/Switch-Toolbox#162]
Loading/Saving a .sbfres that has Japanese/UTF-8 user data will get replaced with "?"'s instead of original text

![UserdataBreak](https://user-images.githubusercontent.com/52844176/70669616-45f58800-1c4d-11ea-8483-bba7434134c2.png)

**Comment by KillzXGaming** [comment]
Sometimes the format is not set to UTF-8 for whatever reason so it breaks. I need to auto detect if it's using these characters and save it back correctly,

**Comment by KillzXGaming** [comment]
Alright it's fixed

![Untitled](https://user-images.githubusercontent.com/13475262/70873091-f62efd80-1f79-11ea-8d78-c04b42912ba7.png)

**Comment by VelouriasMoon** [comment]
Sorry to comment again on a closed issue, But it's fixed on a wii u bfres but a switch bfres still seems to have the same problem

**Comment by KillzXGaming** [comment]
It's fixed now.
