### ISSUE TITLE
Problem with latest version of STB

### ISSUE THREAD

**Issue by emannotava** [KillzXGaming/Switch-Toolbox#163]
So today I decided to update STB to the latest version
Latest version means(Commit: 50c965ae5f658d34bee8001b5e19702a23aecf86, Compile Date: 13-Dec-2019 9:50:57 PM +00:00)

and I know that there was a quick access option added for gfpak files, but upon exporting a entire gfpak file, all the files are now just dumped into 2 folders.

Not sure if that was intentional, but could you please fix/change this so that the files are dumped into this folder structure again:
https://i.imgur.com/n0EqzmB.png

**Comment by KillzXGaming** [comment]
Extracting all files should only export the original file paths. That is so the user can select the folder to repack properly. I added a separation option to extract/replace quick access files in the latest.
