### ISSUE TITLE
UTF-8 user data missing on save

### ISSUE THREAD

**Issue by VelouriasMoon** [KillzXGaming/Switch-Toolbox#165]
Hi i'm back, Well the user data get's loaded now however it is missing on save. Also trying to reopen the bfres in toolbox after saving it just gives me an error. Sorry to keep bring this issue up
![Annotation 2019-12-17 152417](https://user-images.githubusercontent.com/52844176/71027289-52f8f800-20e1-11ea-9350-39bec1970f21.png)
![unknown](https://user-images.githubusercontent.com/52844176/71027416-9bb0b100-20e1-11ea-8ae2-6bb54ddb6df0.png)

**Comment by KillzXGaming** [comment]
Ah i see. Userdata in bntx is so rarely used (this is the only file I know that uses it), I didn't notice that was failing. Should be fixed now https://github.com/KillzXGaming/Switch-Toolbox/commit/57b721c8af4e75129393d62cdda8439d57856f01
