### ISSUE TITLE
nutexb texture replace error

### ISSUE THREAD

**Issue by hamdan1991** [KillzXGaming/Switch-Toolbox#17]
i've downloaded your switch toolbox 8.4BETA and there is a problem. Every time i want to replace the nutexb file with my custom texture i get an "Unhandled exception occurred" error message and at the bottom it says "Not finished yet!. can you please help me solve this issue. I've downloaded your other toolbox versions and every time i build it with visual studio i get a lot of errors. Please help me.

**Comment by hamdan1991** [comment]
i really want to texture mod in smash ultimate but it's impossible if i can't replace my nutexb file.

**Comment by hamdan1991** [comment]
<img width="586" alt="error" src="https://user-images.githubusercontent.com/45534967/49340027-46e4f880-f68e-11e8-8aa7-c14747ceb52c.png">

**Comment by hamdan1991** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Not finished yet!
   at FirstPlugin.NUTEXB.NuTex.Replace(Object sender, EventArgs args) in C:\Users\Nathan\Documents\GitHub\Switch_Toolbox\Switch-Toolbox - Copy\Switch_FileFormatsMain\FileFormats\Texture\NUTEXB.cs:line 218
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.Command.DispatchID(Int32 id)
   at System.Windows.Forms.Control.WmCommand(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Switch_Toolbox
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/Switch_Toolbox.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Switch_Toolbox.Library
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/lib/Switch_Toolbox.Library.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.4.0
    Win32 Version: 3.0.4.0
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/lib/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.4.0
    Win32 Version: 3.0.4.0
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/lib/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
GL_Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/lib/GL_Core.DLL
----------------------------------------
FirstPlugin.Plg
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/Lib/Plugins/FirstPlugin.Plg.dll
----------------------------------------
Syroot.NintenTools.NSW.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/lib/Syroot.NintenTools.NSW.Bfres.DLL
----------------------------------------
Syroot.Maths
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/lib/Syroot.Maths.DLL
----------------------------------------
OpenTK
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/lib/OpenTK.DLL
----------------------------------------
Syroot.NintenTools.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/Lib/Plugins/Syroot.NintenTools.Bfres.DLL
----------------------------------------
Syroot.NintenTools.NSW.Bntx
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/lib/Syroot.NintenTools.NSW.Bntx.DLL
----------------------------------------
BarsLibrary
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/lib/BarsLibrary.DLL
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/lib/OpenTK.GLControl.DLL
----------------------------------------
SFGraphics
    Assembly Version: 1.0.6842.8428
    Win32 Version: 1.0.6842.8428
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/lib/SFGraphics.DLL
----------------------------------------
Syroot.BinaryData
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/lib/Syroot.BinaryData.DLL
----------------------------------------
SARCExt
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/lib/SARCExt.DLL
----------------------------------------
DirectXTex
    Assembly Version: 0.0.0.0
    Win32 Version: 
    CodeBase: file:///I:/Switch%20Hacks/=-=-LayeredFS%20Files-=-=/SuperSmashBrosUltimate/~MOD-TOOL~%20Switch_Toolbox.v0.8.4.BETA/lib/DirectXTex.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by KillzXGaming** [comment]
It says not finished because it is unfinished atm. Will be supported soon when i fix a particular issue.

**Comment by hamdan1991** [comment]
And once you fix the issue, will the updated toolbox be available for download under the 'releases Tab'? Reason why I'm asking is because I always have problems building from visual studo

**Comment by hamdan1991** [comment]
Thank you very much killzxgaming  the main thing that matters to me is the
nutexb fix. Amazing work keep up the good work.

**Comment by hamdan1991** [comment]
I've got another question to is it possible right now to replace textures
inside the nutexb?

**Comment by hamdan1991** [comment]
> Yes I try to update the releases very often. I'll note when it gets fixed in the update notes

Hi friend, is there any possible way right now to replace the texture file inside the nutexb? Please if there is, tell me, i've seen your fire mario texture on twitter and it's obvious that its possible please reply back to me asap.

**Comment by KillzXGaming** [comment]
The latest one now can. Keep in mind it only injects DDS for now as i'm having issues compressing BC7, and also  the format and width/height must be same as original! I kept these limits as arc can't add bigger files afaik but will be fixed when possible.

**Comment by hamdan1991** [comment]
Hi friend thank you very much. So the dds file has to only be bc7? No
problem with that I've got plugins installed on my photoshop that can ooen
bc7 dds
