### ISSUE TITLE
[Regression] Batch Export Texture

### ISSUE THREAD

**Issue by menoanie** [KillzXGaming/Switch-Toolbox#171]
When trying to export the Layout.pack of Splatoon 1 (of the JP update) with the latest commit I get an error shortly after.

However it was working fine before. (works fine with the files of commit 60e09b851139fa538d051fc2e9be3360b7203e9b)

**Comment by KillzXGaming** [comment]
Can you specify the error? Maybe put it in a pastebin? I can't replicate it with the wii u games i have.

**Comment by menoanie** [comment]
Error:
![image](https://user-images.githubusercontent.com/58107955/71640198-aa709980-2c85-11ea-8025-6d5d421406f0.png)

Folders extracted before the error:
![image](https://user-images.githubusercontent.com/58107955/71640199-b9574c00-2c85-11ea-8344-5fb384f11ac1.png)

**Comment by menoanie** [comment]
fixed in the current version
