### ISSUE TITLE
Some textures appear to be a bit off on some models

### ISSUE THREAD

**Issue by VideoGamePlayer7** [KillzXGaming/Switch-Toolbox#172]
Hello. So, I was just looking at some BFRES files from Mario Tennis: Ultra Smash, when I saw that some of the textures were off than what they were expected to be. I'll use the Sprixie Princess as an example because the texture file is mostly off on her when her model is viewed in Toolbox.

Here's the texture file:
![youseihime_green_alb](https://user-images.githubusercontent.com/35055705/71637004-5ebee100-2bee-11ea-8c63-7d2380c99f68.png)

Now here are some screenshots. The top one is the T-posed model with all the polygons selected (besides the racket), the middle one is the T-posed model with some objects unchecked to make the Sprixie smile, and the third screenshot is a single frame on an animation being played on the model.

![bandicam 2019-12-31 17-09-05-211](https://user-images.githubusercontent.com/35055705/71637236-b1020100-2bf2-11ea-9927-452c63bb85e2.jpg)
![bandicam 2019-12-31 17-11-00-482](https://user-images.githubusercontent.com/35055705/71637238-c5de9480-2bf2-11ea-9a43-bba6d38dff75.jpg)
![bandicam 2019-12-31 17-12-23-982](https://user-images.githubusercontent.com/35055705/71637239-cb3bdf00-2bf2-11ea-8410-d31d7d35ecc4.jpg)

As you can see, the solid black parts of the texture are not supposed to be shown in the model, but they just showed up anyway. Also, you can see that the crown is her skin color, but not yellow. Also, the mouth is a solid color, while the part of the texture supposed to be used for the mouth can be seen on her plate and also the other part on her hair. Can anyone try to help me with this issue or make a bugfix if you can please?

Nintendo sure loves their texture mirroring.

**Comment by KillzXGaming** [comment]
Can you send a sample file? It's possibly handling UVs by material parameters which aren't all viewed with the tools shaders atm.

**Comment by VideoGamePlayer7** [comment]
[hereitis.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/4021258/hereitis.zip)
Here's the file. I had to zip it because it wouldn't let me use the original file...

**Comment by KillzXGaming** [comment]
![Capture](https://user-images.githubusercontent.com/13475262/71755858-b5305780-2e5a-11ea-98a7-0c2c08bb22e6.PNG)

It appears these parameters work. The newest commit will work, though I do need to add an option for exporting these.

**Comment by VideoGamePlayer7** [comment]
So, do you mean the experimental release? How were you able to get to the ParamValueDialog? Because the texture parameter settings in the "Sans's Toolbox" version looked different than from in your screenshot.

**Comment by KillzXGaming** [comment]
Yes. The older one is extremely outdated. The dialog is from the para

**Comment by VideoGamePlayer7** [comment]
Thanks... I loaded it up with the latest commit, and everything appeared as intended. :)
