### ISSUE TITLE
Apak archives editing

### ISSUE THREAD

**Issue by wwwklopar** [KillzXGaming/Switch-Toolbox#178]
Hello! Please, can you add possibility to save changes in .apak archives with models? We are doing translation for TMS and reworking textures for some models.

**Comment by wwwklopar** [comment]
Here are samples from Wii U and Switch: https://drive.google.com/file/d/1Ksh1w3ZtxEvZsZhgZoAsVMIkACtbNx4P/view?usp=sharing
Probably file order must be maintained, cause simple rebuild crashes the game

**Comment by KillzXGaming** [comment]
Do you have any more samples of files? Maybe with more than 3 files? I'm still uncertain what 0xC does.

**Comment by wwwklopar** [comment]
> Do you have any more samples of files? Maybe with more than 3 files? I'm still uncertain what 0xC does.

Sure. 4 more samples from both of consoles. Each have more than 3 files.
https://drive.google.com/file/d/1GGyGU_fQeTEzwzWbg_dX55BYFmvAJAdN/view?usp=sharing

**Comment by KillzXGaming** [comment]
Added support however before i close this, i would like someone to test out support. Files get replicated 1 to 1 besides the padding at the very end of the archive (I can't figure out how they do that).

**Comment by wwwklopar** [comment]
Thanks! Will test it in 1 hour after repacking the whole cpk.

**Comment by wwwklopar** [comment]
> Added support however before i close this, i would like someone to test out support. Files get replicated 1 to 1 besides the padding at the very end of the archive (I can't figure out how they do that).

I tried to test archives and here are results: 
1) i just replaced files without repacking and game crashes
2)i tried to repack archive with full data extraction and game still crashes

**Comment by KillzXGaming** [comment]
What about resaving without any edits?

**Comment by wwwklopar** [comment]
Oh... I will try this

**Comment by wwwklopar** [comment]
With just resaving game works. I will try after work with changing again.

**Comment by KillzXGaming** [comment]
Seems it didn't save opened file formats but now that's fixed. Replacing looks fine to me, it adjusts the file size correctly. I do suggest replacing a file that's not too big compared to the original, i don't know if this game has small size restrictions. Also does this format have any other tools that might be useful to use as a reference?

**Comment by wwwklopar** [comment]
I tried 5 more archives and evey one of them crashes the game. I really don't know the reason, but i assume that problem is in BFRES model then. Changed model is bigger than original only on 23kb, so i am not sure if problem is in size... I know only two programs except yours: 
1)QBms
2)Apak_tools (Wii U only and without source code)
All archives that were made with them are crashing the game, even if you will repack archive without changes, so i get the best result at this moment only with your Toolbox.

**Comment by KillzXGaming** [comment]
Where could i find Apak_tools? Is it capable of repacking files from scatch?

**Comment by wwwklopar** [comment]
I hope that it's creator will not mind if I will share it here, but i will delete this link later (It's creator shared it with me so i'm not sure that you can find it anywhere)
https://drive.google.com/file/d/1ORrvi8Bpp_dmrHQmuovHB_5HitN9kPq8/view?usp=sharing
It unpacks files from archive in folder and then can repack them from this folders, but if i'm not mistaken it not maintaines size or file order, so there are crashes after booting the game.

**Comment by KillzXGaming** [comment]
What about simply replacing a texture in the bfres, would that give issues? Models can sometimes be picky with shaders so they are harder to debug. Also what .cpk tool do you use? I'll try messing with this myself.

**Comment by wwwklopar** [comment]
I put it wrong. For models i'm just replacing textures and nothing more at this moment. I can upload original and changed BFRES if this can help. For .cpk i'm using cpkmakec with handmade .csv for compression. I can upload it to. By the way, I joined your discord, so if this will be easier to chat i can DM you there.

**Comment by KillzXGaming** [comment]
Yeah sure you can DM me the csv and bfres changes on discord and i'll check what's wrong.
