### ISSUE TITLE
Exception when clicking a texture in a matertial

### ISSUE THREAD

**Issue by jdperos** [KillzXGaming/Switch-Toolbox#179]
Exception thrown in GX2.cs, line 735:

> System.ArgumentException
>   HResult=0x80070057
>   Message=Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
>   Source=mscorlib
>   StackTrace:
>    at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
>    at System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length)
>    at Toolbox.Library.GX2.Decode(GX2Surface tex, Int32 ArrayIndex, Int32 MipIndex, String DebugTextureName) in M:\BotW\Switch-Toolbox\Switch_Toolbox_Library\Texture Decoding\Wii U\GX2.cs:line 735
>    at Bfres.Structs.FTEX.GetImageData(Int32 ArrayLevel, Int32 MipLevel, Int32 DepthLevel) in M:\BotW\Switch-Toolbox\File_Format_Library\FileFormats\BFRES\Bfres Structs\SubFiles\FTEX.cs:line 604
>    at Toolbox.Library.STGenericTexture.GetBitmap(Int32 ArrayLevel, Int32 MipLevel, Int32 DepthLevel) in M:\BotW\Switch-Toolbox\Switch_Toolbox_Library\Generics\Texture\GenericTexture.cs:line 527
>    at FirstPlugin.Forms.SamplerEditor.<>c__DisplayClass13_2.<textureRefListView_SelectedIndexChanged>b__1() in M:\BotW\Switch-Toolbox\File_Format_Library\GUI\BFRES\Materials\SamplerEditor.cs:line 299
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

Repro steps:
1. Load all BotW BFRES files (model, tex1, tex2, animation) for any model, for instance Npc_Gerudo_Queen.
2. Expand down to : Npc_Gerudo_Queen > Models > Npc_Gerudo_Queen > Materials > Select Mt_Body
3. In the Textures tab, select one of the textures associated with the material.
4. Tool will crash

**Comment by KillzXGaming** [comment]
Should be fixed now. https://github.com/KillzXGaming/Switch-Toolbox/commit/f090f7e757d2372a57bfe80977acecb64173293f
