### ISSUE TITLE
Wii U BFRES Animation Export error

### ISSUE THREAD

**Issue by YoshiCrystal** [KillzXGaming/Switch-Toolbox#18]
Hi, I wanted to extract some bfska files from Wii U BFRES but everytime I try to extract an animation, i got an error. 
![image](https://user-images.githubusercontent.com/24484608/49446528-afd68880-f7d4-11e8-9b85-11b7bf03fd18.png)

Ik the error its in spanish

**Comment by KillzXGaming** [comment]
bfska export/replace properly now.
