### ISSUE TITLE
Animations saved as *.SMD don't work in Blender

### ISSUE THREAD

**Issue by AtomicLugia** [KillzXGaming/Switch-Toolbox#180]
Blender version: 2.78b
Blender Source Tools version: 2.10.2

When I try to import an animation saved as *.SMD on a *.DAE file (both are exported via Switch Toolbox), it doesn't work. It shows a bunch of traceback errors despite matching model.

Here are the files to check for yourself:
[govacation_scubathingy.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/4118133/govacation_scubathingy.zip)

**Comment by AtomicLugia** [comment]
Doesn't work with the latest version of Blender and Blender Source Tools either.

**Comment by KillzXGaming** [comment]
Those work perfectly fine for me. Can you show the trace error?

**Comment by AtomicLugia** [comment]
Okay, it works on me as well but looks glitchy as heck. Maybe an option to save models as SMD would lift it?

**Comment by KillzXGaming** [comment]
The models are related to this which atm I don't know why they are orientated wrong. https://github.com/KillzXGaming/Switch-Toolbox/issues/175. I'd prefer to stick with dae and fbx since those support mostly all the needed features modern model formats require.

**Comment by KillzXGaming** [comment]
This should fix the last of the SMD isses https://github.com/KillzXGaming/Switch-Toolbox/commit/9918b811a8fe78157bcea31e3488f7539c6b89f4
