### ISSUE TITLE
Add support for large WTA files (Go Vacation + possibly other Switch games)

### ISSUE THREAD

**Issue by AtomicLugia** [KillzXGaming/Switch-Toolbox#181]
I found some WTA files, which are very huge. They're likely archives that I can't open. It seems that the large WTA files found in Go Vacation contains all the outfits and other stuffs from that game. They can be found in the ROM of Go Vacation in: "Romfs\Raw\Character\*.wta"

**Comment by KillzXGaming** [comment]
Do they have a wtb file too? Astral chain actually had wta/wtb for textures though i haven't checked go vacation games files. Maybe send a sample?

**Comment by AtomicLugia** [comment]
They come without *.WTB files. They're also pretty huge. There's "all_model_pack.wta", which is 30 megs and "all_model_pack_tex.wta", which is almost a gig.

Here's one of them:
https://www.dropbox.com/s/11rw5hb25do6ko1/all_model_pack.wta?dl=0

**Comment by KillzXGaming** [comment]
I see. It's a giant archive and the file data is zlibbed.

**Comment by KillzXGaming** [comment]
![Capture](https://user-images.githubusercontent.com/13475262/73321761-7bf8c680-4211-11ea-9ac3-fa4fea72a049.PNG)

Added support.

**Comment by KekMcGee** [comment]
all_model_pack_tex.wta is decompressed by default, which toolbox is refusing to open. just in case it's needed https://mega.nz/#!opQxQCrS!FAKfhaJY-AXMV0NBOV66Dy3lLDXPBAw_vsEItS-78B8

**Comment by AtomicLugia** [comment]
I can't open it either, it shows an error message

**Comment by KillzXGaming** [comment]
Wow this format is starting to make less sense to me. I cannot get the data offsets correct for that one.

**Comment by AtomicLugia** [comment]
They're definitely the textures for the models in all_model_pack.wta, since they don't have any textures.

**Comment by AtomicLugia** [comment]
Will it be possible to access these files, too? We're so close.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/5ce973f3e77f5d9907c349f6297f387040ce6a1d

**Comment by AtomicLugia** [comment]
I can finally open the large "all_model_pack_tex.wta" file. I managed to extract everything from this file. However, most of these files are just "File XXXX" files that contains mostly a garble of chinese letters (probably encrypted or buggy extraction). Also, some BNTX files can't be opened, it shows another exception. Maybe the extraction process isn't completly working here. I included some files as an example here. But this is definitely a step closer!
[bruh.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/4195359/bruh.zip)

**Comment by KillzXGaming** [comment]
All files should now open https://github.com/KillzXGaming/Switch-Toolbox/commit/43d0a498b5a0c6c2bc702793c54c897192d94d20

**Comment by AtomicLugia** [comment]
It works like a charm! There are only very few files labelled "File XXXX" which won't work but it's basically nothing compared to all the files that work. However, when I try to extract all files from the large WTA file, an annoying exception occurs when it comes to one of these "files", which makes it impossible to extract the entire archive. A workaround could be a way to select multiple files within the archive to extract all of them except the "File XXXX" files or just ignoring all files during extraction that starts with "File" to avoid exceptions.
