### ISSUE TITLE
Saving BFLYT causes icon errors in Splatoon

### ISSUE THREAD

**Issue by slashiee** [KillzXGaming/Switch-Toolbox#183]
When saving BFLYT, certain icons turn into question marks
Before:
<img width="641" alt="2020-01-28_14-57-18" src="https://user-images.githubusercontent.com/15317421/73312895-a715f280-41de-11ea-879c-7af3381273a7.png">
After:
<img width="641" alt="2020-01-27_15-32-35" src="https://user-images.githubusercontent.com/15317421/73312874-982f4000-41de-11ea-89d9-e790e29cd441.png">

**Comment by KillzXGaming** [comment]
What bflyt did you edit and where is it located at?

**Comment by slashiee** [comment]
I edited `Cst_CustomizeTV_00.bflyt` in `content\Pack\Layout.pack\Layout\Cst_CustomizeTV_00.szs\Cst_CustomizeTV_00.arc\blyt`

**Comment by KillzXGaming** [comment]
Thanks. This was an issue from the text encoding not saving right so it should be fixed now https://github.com/KillzXGaming/Switch-Toolbox/commit/f090f7e757d2372a57bfe80977acecb64173293f

**Comment by slashiee** [comment]
Trying the latest version, the issue seems to still be present.
<img width="641" alt="2020-01-29_13-56-35" src="https://user-images.githubusercontent.com/15317421/73401104-5914f380-429f-11ea-9837-b78dc22a4821.png">

**Comment by KillzXGaming** [comment]
Is this redone on the original szs? I tried saving that bflyt and it came out identical with the original.

**Comment by KillzXGaming** [comment]
I noticed i forgot to push the part that saves the text transform offset so that might fix it https://github.com/KillzXGaming/Switch-Toolbox/commit/2d18e4bbdc08af72637174c41311f42971ed6d50

**Comment by slashiee** [comment]
Issue is fixed now, thank you!
<img width="641" alt="2020-01-29_14-53-50" src="https://user-images.githubusercontent.com/15317421/73404814-3edf1380-42a7-11ea-9fe8-d32a2b7bd337.png">
