### ISSUE TITLE
bntx replacement

### ISSUE THREAD

**Issue by AshleyMiller9696** [KillzXGaming/Switch-Toolbox#190]
if i use the toolbox, ingame (MK8D) there seems to be a gray film above the image
-> if I use bntx injector there isn't a problem

// thanks for the tool!

**Comment by KillzXGaming** [comment]
Can you send one from toolbox and one with bntx injector?

**Comment by AshleyMiller9696** [comment]
![bntx](https://user-images.githubusercontent.com/56538976/73971548-61180780-491f-11ea-8835-4e2eac806a21.jpg)
![toolbox](https://user-images.githubusercontent.com/56538976/73971554-6412f800-491f-11ea-9d7d-efb2361aaefd.jpg)

**Comment by KillzXGaming** [comment]
Well it looks to be an SRGB issue so it's just an issue with the settings. Make sure you have SRGB enabled in the properties. 

![image](https://user-images.githubusercontent.com/13475262/73981891-3a4ad880-4901-11ea-86b2-c6f5216b0984.png)
