### ISSUE TITLE
cadence of hyrule sprites tiling problem

### ISSUE THREAD

**Issue by steventylerseanherr** [KillzXGaming/Switch-Toolbox#192]
i was trying to dump cadence of hyrules sprites and noticed that some of the sprites were mangled and missing tiles
i asked in the vg resource discord and random talking bush says that somethings wrong with the tiling algorithm

for reference this is what i get from switch toolbox
![grasslands_tree_big](https://user-images.githubusercontent.com/48705919/74618784-3426da00-5101-11ea-9be2-3bc3d5fd702d.png)
and this is what random talking bush got from his own scripts
![grasslands_tree_big](https://user-images.githubusercontent.com/48705919/74618825-54ef2f80-5101-11ea-86fa-1a632d5f486f.png)

**Comment by KillzXGaming** [comment]
Can you send the texture as a .bfres?

**Comment by steventylerseanherr** [comment]
yes and sorry for the wait

uh maybe not
oh i can zip it and send that
[grasslands_tree_big.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/4228360/grasslands_tree_big.zip)

**Comment by KillzXGaming** [comment]
Huh I have no issues myself?
![image](https://user-images.githubusercontent.com/13475262/75077790-c2200d80-54d1-11ea-9ea2-a2e3ad44fd0d.png)

**Comment by steventylerseanherr** [comment]
how do i export as a bntx?
all ive got is bftex and normal picture formats
(also i cant download the latest updates on my slow internet without timing out so that might have something to do with it.  my toolbox says 
![image](https://user-images.githubusercontent.com/48705919/75124119-1fa38e00-567b-11ea-9cdf-8472007c736b.png) but ill keep trying on that)

**Comment by steventylerseanherr** [comment]
got it
![image](https://user-images.githubusercontent.com/48705919/75124658-b4f45180-567e-11ea-89bb-8a5ef3d91b43.png)
one of the comments since i last sat through an update must of fixed it
so i guess i close this issue?

**Comment by KillzXGaming** [comment]
Yeah seems fine to me. Not sure what could've caused it tbh
