### ISSUE TITLE
BotW Wii U Mipmap refs persist after deletion

### ISSUE THREAD

**Issue by GingerAvalanche** [KillzXGaming/Switch-Toolbox#200]
When replacing or deleting/reimporting a texture in a Wii U texture bfres for BotW, toolbox should generate new mipmaps for the texture.

Instead, the previous mipmap references stick around in memory, causing any texture that is imported with the same name as an old file to use the old file’s mipmaps instead of generating new ones.

This can be worked around by exporting the texture with old mipmap refs, deleting it in the bfres, saving, closing toolbox, then opening it and importing the texture again.

**Comment by KillzXGaming** [comment]
I am unsure on replicating this. I opened a tex1 sbfres with a tex2 next to it. Exported an image. Edited it and also deleted the original. Importing the edited image and it works with with mips. Doing the same process but replacing instead and that also works fine.

**Comment by GingerAvalanche** [comment]
Will see if I can test tonight, but it will be several hours before I’m able to. Thanks.

**Comment by GingerAvalanche** [comment]
Sorry it took so long. That did, indeed, fix this. Closing.
