### ISSUE TITLE
Deleting Vertex Buffers raises exception

### ISSUE THREAD

**Issue by GingerAvalanche** [KillzXGaming/Switch-Toolbox#203]
Deleting a vertex buffer will almost always raise an error regarding a buffer index that has no attributes.

I believe the code is trying to reference the properties of the buffer after it has deleted them but before the buffer itself is deleted. (Or, at the very least, before it is removed from the array of buffers)

No currently known workaround

**Comment by KillzXGaming** [comment]
This should fix it (I can no longer get any errors from removing these) https://github.com/KillzXGaming/Switch-Toolbox/commit/dc9696544052d53b0401080affeecb8d62a22d31
