### ISSUE TITLE
Paper Mario Colour Splash .LZ

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [KillzXGaming/Switch-Toolbox#212]
Decompression is already possible for these with toolbox but it's rather a pain having to do it for each file to open the decompressed contents in toolbox, so detecting the type and opening much like a SARC or SZS would be nice!

**Comment by CosmicDreamsOfCode** [comment]
Nvm I was mistaken. The LZ compression isn't supported but I'm pretty sure there's a BMS script floating around for it.

**Comment by CosmicDreamsOfCode** [comment]
`# Paper Mario: Color Splash - File Decompression
# Written by Random Talking Bush

endian little
comtype COMP_LZ77WII_RAW11

get ZSIZE asize
math ZSIZE - 16
goto 4
get SIZE long
get NAME basename
clog NAME 16 ZSIZE SIZE

endfunction
`
Here's that BMS script if it helps!

**Comment by KillzXGaming** [comment]
Added https://github.com/KillzXGaming/Switch-Toolbox/commit/ab37acc60c6602e4dbcee9c2f4b0a81e95246da6

**Comment by blackbe** [comment]
Do you know how to compress it again in the same LZ77WII_RAW11 format?  I can't seem to find anything that actually works.  I'm working on this project for my 10 year old daughter for Christmas and I'm not coming up with anything.  Any help would be greatly appreciated.
