### ISSUE TITLE
NUTEXB cubemaps not replacing properly

### ISSUE THREAD

**Issue by MegAmi24** [KillzXGaming/Switch-Toolbox#217]
Trying to replace textures in .nutexb files with more than one array (e.x. cubemaps) doesn't seem to work properly. Exporting each texture works fine, but trying to replace one will always replace the first array - even if it isn't being viewed - and make the rest black.

Cubemap face view on an unmodified file:
![image](https://user-images.githubusercontent.com/7158344/79057575-5e3fd880-7c28-11ea-9732-675e53591eae.png)
Cubemap face view after replacing a texture:
![image](https://user-images.githubusercontent.com/7158344/79057583-757ec600-7c28-11ea-8cad-42ffc70e421a.png)

**Comment by KillzXGaming** [comment]
You must use a .DDS format currently as it supports multiple array levels

**Comment by MegAmi24** [comment]
> You must use a .DDS format currently as it supports multiple array levels

I tried using a DDS file and the textures were corrupted when imported.
![image](https://user-images.githubusercontent.com/7158344/79077343-8c73f580-7cc6-11ea-89ae-3464923dd16e.png)

**Comment by KillzXGaming** [comment]
Is it the same format as the original?

**Comment by MegAmi24** [comment]
> Is it the same format as the original (usually BC6)?

I saved it as BC6, but the textures are still jumbled up.
![image](https://user-images.githubusercontent.com/7158344/79081112-fd73d700-7cdf-11ea-8ae1-77f16a8bedda.png)

**Comment by KillzXGaming** [comment]
Should be fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/9f43146966b0b058eee6c716b653cf07d513f299
