### ISSUE TITLE
Request Feature: Option to set exported filetype as default

### ISSUE THREAD

**Issue by natepley** [KillzXGaming/Switch-Toolbox#223]
I'm exporting hundreds of textures as png.  Because the default export filetype is always bftex, I have to manually change it every time, which is very tiring.  If I could set png to be the default filetype for exporting, that would save me a lot of pain.

**Comment by Machow8** [comment]
Hi,

There is the 'Batch export textures (all supported formats)' alternative (which you can access from tools tab).

You'll only need to setup the desired export format (like png) once after you had choose the files which you wanna extract from and the folder where you wanna program save at what is gonna be extracted.

Simple as that.

**Comment by natepley** [comment]
Thank you!  I wish I'd noticed that sooner.  It would have saved me a lot of time.  I guess this issue is not needed anymore.
