### ISSUE TITLE
Texture importer broken on newest commit

### ISSUE THREAD

**Issue by melsbacksfriend** [KillzXGaming/Switch-Toolbox#232]
I tried replacing textures in bntx format and also tried creating some bntx files, but the program just crashed when I opened an image.  This happened with every image I tried.  It was working just fine before the update.  In case this is GPU related, my computer has an AMD Radeon R7 and is a cheap HP laptop with a few upgrades.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/6aa22316e24dab363564e79093b9e6077bf834bb
