### ISSUE TITLE
I can't save my changes

### ISSUE THREAD

**Issue by Blendskill** [KillzXGaming/Switch-Toolbox#233]
I want to modify files of my game which is in .xci format. But whatever I modify (3d model, texture...), the save button is grayed out and I cannot save my modifications.
Is it a bug or I just don't know how to use Toolbox?

**Comment by KillzXGaming** [comment]
You can't save XCI files in the tool and it's not planned since it's really unnecessary for altering game files. You right click any files edited in the tree and save them that way. Then you use layeredFS and load the files from the path structure.
