### ISSUE TITLE
Exporting models from BFRES appears not to work

### ISSUE THREAD

**Issue by ComputerBot2016** [KillzXGaming/Switch-Toolbox#24]
When I try to export models found in .BFRES files for Splatoon 2, the output generated never appears to be valid. 

Exporting to .obj results in a file that doesn't contain any model data whatsoever.
Exporting to .dae looks like valid when opened in Notepad++, but when opened in 3D modeling/viewing software, various generic errors are thrown (no details are given) or the program ends up not loading anything at all (importing into Unity3D did this).
Exporting to .fbx just generates another .dae file with the same problems
Exporting to .csv gives this error http://prntscr.com/lxm9js and no file is created

**Comment by KillzXGaming** [comment]
Atm you'll need to convert the .dae with noesis and open that with another program.

**Comment by KillzXGaming** [comment]
Now .dae should open fine. I'll look into .obj and .fbx some other time

**Comment by KillzXGaming** [comment]
Should be fixed now on current commit
