### ISSUE TITLE
How to understand the JSON format?

### ISSUE THREAD

**Issue by Blendskill** [KillzXGaming/Switch-Toolbox#240]
Toolbox can export 3d models in json format, but I can't find any documentation about this format.
Everything is pretty intuitive, but I don't understand how the "Meshes" class works.
I don't understand the meaning of all the values present in the subcategories "Polygons" and "Datas".

Can you explain to me ? And do you know 3D editing software that can modify this format?
I don't want to use the dae format because there is a bug with it.

**Comment by KillzXGaming** [comment]
It's not a model format that can be used elsewhere.  It's a text based format for easier editing of the format. Exporting as dae should be good enough. If you have bone issues you should use another program like 3ds max and import/export through that or use the gfbmdl max script.
