### ISSUE TITLE
Comma ( , ) instead of Dot ( . ) in SMD (.gfbanm) export on french windows

### ISSUE THREAD

**Issue by Megurine** [KillzXGaming/Switch-Toolbox#249]
Hi team !
I have an issue with Toolbox when I export an animation from Pokemon S/S ( .gfbanm to .SMD) all the float values are wrote with a comma instead of a dot.
`102 5,812716 2,087815E-08 4,440892E-15 -3,067556 0,9164947 -3,046435`
instead of 
`102 5.812716 2.087815E-08 4.440892E-15 -3.067556 0.9164947 -3.046435`

SMD plugins are so lost ^^

Other guys have dots, so I supose its my windows (French with AZERTY keyboard).
I can dev a really lite tool to convert many SMD at once but it would be nice if it can be fix directly in Toolbox (directly in code or with a "float seperator char" in config).

Thank you !

**Comment by KillzXGaming** [comment]
Could you test on latest? Might be fixed by https://github.com/KillzXGaming/Switch-Toolbox/commit/a8ec469252c0f88cc8844d289a4d20dc6cd6e37a

**Comment by Megurine** [comment]
Nice job, its fixed ! 
Thank you !
