### ISSUE TITLE
The unknown offset in the GFPAK format

### ISSUE THREAD

**Issue by dragonation** [KillzXGaming/Switch-Toolbox#25]
The unknown offset in the GFPAK is the folder hash index offset, including the first hash index offset, all are folder hash index offsets.

So the length of the header is varying according to the number of the folders stored in the gfpak file. Most of the gfpak file has 3 folders, so there are three hash index offset (one is used in the code, the other twos are regarded as unknown offset)

The data structure referenced by the folder index offset is similar to the file hash index, except the index data is the count of files in that folder, not the file index in the contents below.

**Comment by KillzXGaming** [comment]
GFPACK saving is now fixed thank you!
