### ISSUE TITLE
Support for MSBT.LZ File Extension

### ISSUE THREAD

**Issue by andercard0** [KillzXGaming/Switch-Toolbox#250]
Hello! 

Would it be possible to get support for the MSBT.LZ file type? I know i can edit msbt files with Kuriimu normally but this is not the case here with this kind of file. I can open it with Toolbox, edit it but can't save any changes at all! Dunno if this is correct place to raise a ticket to it if not at least i tried : D 

Thank You!

**Comment by KillzXGaming** [comment]
Added a menu for it (Tools - Compression -  LZ77 (Wii Type 11) so you can decompress and edit in kuriimu. I won't add compression yet but i am sure there is something else that could.
