### ISSUE TITLE
Updater Error

### ISSUE THREAD

**Issue by numsei1** [KillzXGaming/Switch-Toolbox#251]
The error occurred when I updated to the latest version.
When I start the program (with the latest version installed), the Updater remains green, so I press it, and all previous updates with a strange date are shown. I press "Yes" but the program just restarts (And everything stays there).

![Capturar_2020_06_14_14_19_13_269](https://user-images.githubusercontent.com/64751947/84599703-61cf2600-ae4a-11ea-8e11-5383ecf32a84.png)

**Comment by KillzXGaming** [comment]
Should be fixed from this and should still update on the current build properly. https://github.com/KillzXGaming/Switch-Toolbox/commit/aaa98afa8ea6f15a0d27b774464204d8e0e1821e
