### ISSUE TITLE
SZS file Znear error

### ISSUE THREAD

**Issue by rveyrand** [KillzXGaming/Switch-Toolbox#253]
latest update can't let szs files (mainly mario kart 8 ones) being loaded properly, displaying a Znear error.

here is the full log about said error (partially in french as being french):

System.ArgumentOutOfRangeException: L'argument spécifié n'était pas dans les limites de la plage des valeurs valides. (specified argument was not in limits of valid values)
Nom du paramètre : zNear
   à OpenTK.Matrix4.CreatePerspectiveFieldOfView(Single fovy, Single aspect, Single zNear, Single zFar, Matrix4& result)
   à OpenTK.Matrix4.CreatePerspectiveFieldOfView(Single fovy, Single aspect, Single zNear, Single zFar)
   à GL_EditorFramework.GL_Core.GL_ControlBase.set_ZNear(Single value)
   à Toolbox.Library.Viewport.LoadViewportRuntimeValues()
   à Toolbox.Library.Viewport..ctor(List`1 container, Boolean LoadDrawables)
   à FirstPlugin.Forms.BfresEditor..ctor(Boolean HasModels) dans C:\projects\switch-toolbox\File_Format_Library\GUI\BFRES\BfresEditor.cs:ligne 104
   à FirstPlugin.BFRES.LoadEditors(Object SelectedSection) dans C:\projects\switch-toolbox\File_Format_Library\FileFormats\BFRES\BFRES.cs:ligne 430
   à Toolbox.Library.Forms.ObjectEditorTree.treeViewCustom1_AfterSelect(Object sender, TreeViewEventArgs e)
   à System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   à System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   à System.Windows.Forms.TreeView.WmNotify(Message& m)
   à System.Windows.Forms.TreeView.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Toolbox
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Toolbox.exe
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Toolbox.Library
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Toolbox.Library.DLL
----------------------------------------
Microsoft.VisualBasic
    Version de l'assembly : 10.0.0.0
    Version Win32 : 14.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DirectXTexNetImpl
    Version de l'assembly : 1.0.0.3
    Version Win32 : 
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/x64/DirectXTexNetImpl.dll
----------------------------------------
System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
OpenTK
    Version de l'assembly : 3.0.1.0
    Version Win32 : 3.0.1
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/OpenTK.dll
----------------------------------------
Octokit
    Version de l'assembly : 0.31.0.0
    Version Win32 : 0.31.0.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Octokit.DLL
----------------------------------------
SFGraphics
    Version de l'assembly : 1.0.6956.42501
    Version Win32 : 1.0.6956.42501
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/SFGraphics.dll
----------------------------------------
OpenTK.GLControl
    Version de l'assembly : 3.0.1.0
    Version Win32 : 3.0.1
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/OpenTK.GLControl.dll
----------------------------------------
System.Net.Http
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
FirstPlugin.Plg
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/Plugins/FirstPlugin.Plg.dll
----------------------------------------
GL_EditorFramework
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/GL_EditorFramework.DLL
----------------------------------------
FlatBuffers
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/Plugins/FlatBuffers.DLL
----------------------------------------
Syroot.NintenTools.NSW.Bfres
    Version de l'assembly : 1.2.3.0
    Version Win32 : 1.2.3.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/Syroot.NintenTools.NSW.Bfres.dll
----------------------------------------
Syroot.Maths
    Version de l'assembly : 1.5.3.0
    Version Win32 : 1.5.3.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/Syroot.Maths.DLL
----------------------------------------
Syroot.NintenTools.Bfres
    Version de l'assembly : 1.2.3.0
    Version Win32 : 1.2.3.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/Syroot.NintenTools.Bfres.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Version de l'assembly : 3.0.6.0
    Version Win32 : 3.0.6.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/Plugins/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
Syroot.NintenTools.NSW.Bntx
    Version de l'assembly : 1.2.3.0
    Version Win32 : 1.2.3.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/Syroot.NintenTools.NSW.Bntx.dll
----------------------------------------
Syroot.BinaryData
    Version de l'assembly : 2.0.1.0
    Version Win32 : 2.0.1.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/Syroot.BinaryData.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Version de l'assembly : 0.0.0.0
    Version Win32 : 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
SPICA
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/Plugins/SPICA.DLL
----------------------------------------
KCLExt
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/Plugins/KCLExt.DLL
----------------------------------------
Newtonsoft.Json
    Version de l'assembly : 12.0.0.0
    Version Win32 : 12.0.1.22727
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/Newtonsoft.Json.dll
----------------------------------------
System.Numerics
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
ZeldaLib
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/Plugins/ZeldaLib.DLL
----------------------------------------
SARCExt
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/rveyr/Downloads/Toolbox/Lib/SARCExt.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

**Comment by rveyrand** [comment]
Quick fix is to simply change a setting in the config.xml. 
change is at line: CameraNear. change it from 0.1 to 1

**Comment by TmixRPG** [comment]
MERCI INFINIMENT !!!! (je suis aussi français)
je viens de me rendre compte que Z c comme dans la 3d et que le Near voulait dire que c etait trop près
