### ISSUE TITLE
Unable to remove Toolbox.exe

### ISSUE THREAD

**Issue by Ruikio** [KillzXGaming/Switch-Toolbox#255]
Whenever I try to remove the software, even though I am the Owner and it shows in the permissions, the executable is preventing me from continuing.

https://cdn.discordapp.com/attachments/600835847410942012/725325322609754152/unknown.png

**Comment by KillzXGaming** [comment]
That means the toolbox is still open. Make sure it's closed with task manager incase it didn't fully close for some reason.
