### ISSUE TITLE
Apart from viewing, it doesnt let you do anything

### ISSUE THREAD

**Issue by TheOGMew3** [KillzXGaming/Switch-Toolbox#26]
I just realised after a week that importing edited files and saving gfpak doesnt really do anything.
When you load the edited file, it still shows the original texture.

And loading the gfpak just flatout crashes the game...

**Comment by KillzXGaming** [comment]
Yeah it's related to this issue https://github.com/KillzXGaming/Switch-Toolbox/issues/25. It's just not saving right (didn't get a chance to test it myself) but it'll be fixed in 0.9
