### ISSUE TITLE
Bug: SMD Animation Export Duplicate Bone Names

### ISSUE THREAD

**Issue by AzureBerylBlue** [KillzXGaming/Switch-Toolbox#263]
For certain animations, when exporting animations as SMD, and attempting to convert them using Noesis, Noesis gives a warning about duplicate bone names, and messes up the conversion. I've attached an example BFRES that causes this problem.

[Example.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/4955920/Example.zip)

**Comment by KillzXGaming** [comment]
Seems to convert fine to fbx. Idk how it's getting that error, but none of the bone names in the .smd are actually duplicates and bfres can't have duplicate bone names either.

**Comment by AzureBerylBlue** [comment]
Never mind, it has nothing to do with bone names. It looks like Noesis does not like animations where no initial position is specified, If I use Notepad to edit Wait.smd from the attached example, and add the line "17 0 0 0 0 0 0" under time 0, the error goes away. Would it be possible to update Switch Toolbox's SMD export to make sure all nodes have an initial position at time 0?
