### ISSUE TITLE
Problem DAE with SMD animation in Blender

### ISSUE THREAD

**Issue by sebastianbrunobautes** [KillzXGaming/Switch-Toolbox#264]
can someone tell me why this happens
first I import the DAE model
then I import the .smd animation which generates an armature for the model
I assign the armature to the DAE model and deform it
even if I remove the existing armature and assign a new one
the model is deformed
and apparently uv mapping doesn't work either
like in the right shoe
![Sin título](https://user-images.githubusercontent.com/60292226/88124375-5981ad80-cba3-11ea-99ef-38aaec2c6ffb.png)

**Comment by sebastianbrunobautes** [comment]
somebody thinks it's the orientation of the bones
how do I solve it

**Comment by sebastianbrunobautes** [comment]
![Sin título2](https://user-images.githubusercontent.com/60292226/88128713-e7ae6180-cbac-11ea-999c-85c93c12149b.png)

**Comment by sebastianbrunobautes** [comment]
this happend when import dae model with smd animation exported both from Switch-Toolbox, solution ?

**Comment by KillzXGaming** [comment]
Afaik it's a model issue with the bones. For some reason, the bone's aren't in the right axis position for animations to work right, and I'm not sure on fixing it atm. You can load the bfres in 3ds max, then export as fbx and back to blender and it should work (or directly import the bfres into max with the 3ds max script).

**Comment by sebastianbrunobautes** [comment]
3ds max supports bfres or do you need a plugin?  Where can i download it?

**Comment by sebastianbrunobautes** [comment]
I did not know Toolbox, it is an amazing, powerful tool, if I had not known it I could not have imagined it better, congratulations to the whole team

**Comment by KillzXGaming** [comment]
Here you can try this script which is on this page https://www.vg-resource.com/thread-29836.html

**Comment by sebastianbrunobautes** [comment]
Thanks
