### ISSUE TITLE
3D World stage Byml crashes from too many reference nodes.

### ISSUE THREAD

**Issue by vgisuruex** [KillzXGaming/Switch-Toolbox#27]
i tried unpacking the level files and opening the byml but then switch toolbox crashed. this happens every time i open level byml files but works fine with some other level files. the same thing happens for 4th dimension 3d land level editor's byml editor and odyssey level editor's byml editor. can you help pls?

Thanks in advance!

**Comment by KillzXGaming** [comment]
Can you name an example byml? Ones I've tried open fine.

**Comment by vgisuruex** [comment]
here's a link to the file i tried : https://ufile.io/87cie
also the 3d world editor, red carpet works with this byml : https://github.com/masterf0x/RedCarpet
most of the tools gets me the error StackOwerflowExpection or something like that.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/c922ff1e4ffd675486ceeabf4dda197c5fcc6d34
