### ISSUE TITLE
Crashing seemingly at random

### ISSUE THREAD

**Issue by LozoTrioxide** [KillzXGaming/Switch-Toolbox#270]
The toolbox seems to be crashing at random in the middle of editing items, seems to do it most of the time if a couple textures are loaded at one time

Not sure what else to put here?

Im on the latest version with DirectX and the other thing

**Comment by KillzXGaming** [comment]
What do you mean by editing items? Is there a specific file/game that this occurs on that can be replicated easily?

**Comment by LozoTrioxide** [comment]
Uhh well i was editing the linkle mod and the Hyrule Rebalance Dyes module and i was changing the texture of a model, and when i go to select the texture for it to use or when it displays the texture in the bottom right of the screen it crashes, sorry i cant be more heopful, i might be able to get some kind of video

**Comment by KillzXGaming** [comment]
Did you open .tex2 files by any change? Only tex1 should be open. Could be possible it tries to load tex2 instead and crashes (those only store mipmaps by itself)

**Comment by LozoTrioxide** [comment]
I did yeah, i wont open those next time and see if it fixes it, ill let you know c:

**Comment by KittenPixel-cell** [comment]
Im trying to edit a mod it only has tex2 so idk what to do

**Comment by KittenPixel-cell** [comment]
in the TitleBG.pack

**Comment by KillzXGaming** [comment]
Tex1 files are outside the pack and in the models folder.
