### ISSUE TITLE
Crash when replacing Wii U kcl and using material editor

### ISSUE THREAD

**Issue by Souperman9** [KillzXGaming/Switch-Toolbox#274]
I've been trying to replace kcl's in 3DW, but whenever I do (and select materials using the preset editor), it ends up displaying a loading bar that hangs near the beginning for a few seconds before crashing. It doesn't crash with default materials though.
[BalanceTruck.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/5095954/BalanceTruck.zip)

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/e3ac2625ef81b3fca058a29e60e0a4636a35858a
