### ISSUE TITLE
Prevent Switch Toolbox from saving file extension in NUTEXB internal name when opening by folder

### ISSUE THREAD

**Issue by ThatNintendoNerd** [KillzXGaming/Switch-Toolbox#276]
When opening by folder and saving a NUTEXB file, Toolbox assumes the file name and extension to be the internal texture name, causing the mismatched names to cause issues in Ultimate model viewers and in-game. Sometimes the internal name has capital characters, so Toolbox shouldn't just disregard the extension and save the file name only in the internal name. It should retain the internal name at all times. Unsure of how renaming a NUTEXB internal name could work when opening by folder.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/42c3275efcc607de723979bc3752125d80a44a53
