### ISSUE TITLE
Github Update button enabled when using the latest commit

### ISSUE THREAD

**Issue by Monotek18** [KillzXGaming/Switch-Toolbox#277]
![image](https://user-images.githubusercontent.com/20025273/91162860-f5379980-e6cc-11ea-828e-f4b8e5c53bfe.png)

I use the very last build, and the app tells me that there is a new version

**Comment by KillzXGaming** [comment]
Should be fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/968bd4f65464c225cb5675b5f4537bd316ad86f7
