### ISSUE TITLE
Crash when opening Cafe Layout (*.bflyt) files

### ISSUE THREAD

**Issue by MarioPossamato** [KillzXGaming/Switch-Toolbox#279]
Whenever I try to open any bflyt files, toolbox crashes.  Also, whenever I try to open [this bflyt file](https://cdn.discordapp.com/attachments/559441089459650649/749885065391112202/Edit_LeftParts_00.bflyt) which is from Super Mario Maker 2, toolbox gives me an, "Unable to read beyond the end of the stream." error.  I was wondering if you could look into these and possibly fix them. Thanks! :)

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/88b84a9a8da860b2236e1c150b7bd7e804e86d4e

**Comment by MarioPossamato** [comment]
Sweet!  Thank you :)
