### ISSUE TITLE
Unable to open certain BFRES files

### ISSUE THREAD

**Issue by ComputerBot2016** [KillzXGaming/Switch-Toolbox#28]
I tried to open the BFRES for a stage model from Splatoon 2 and got this error: http://prntscr.com/m6o2sf

I've opened several of the game's BFRES files in the past (including other stage models) with no issue at all. Seems strange that this one causes an issue. For reference, I tried to open the stage model for Blackbelly Skate park (both versions). I can link to the BFRES files if necessary.

**Comment by KillzXGaming** [comment]
It seems to have an unknown format. I'll have it fixed in the next update (0.9)

**Comment by ComputerBot2016** [comment]
thank you
