### ISSUE TITLE
Artifacts on custom 3DW models

### ISSUE THREAD

**Issue by Souperman9** [KillzXGaming/Switch-Toolbox#281]
This _might_ not be an issue related to Switch Toolbox, but I'm fairly sure it is. Whenever I save a custom model with custom textures, I get strange artifacts. This never used to happen previously, and I've included a screenshot of a model made today that was imported perfectly 2 months ago. The artifacts are not present in the viewport.
![image](https://user-images.githubusercontent.com/35243266/92209920-300dae80-eed1-11ea-98c9-b8188ae84c26.png)

**Comment by KillzXGaming** [comment]
This is with importing the custom model aswell and if so did you use the 3D World preset? Prevents any weird glitches if it's used.

**Comment by Souperman9** [comment]
I used the preset for the kcl, but this was for when I was creating a simple guide, so I didn't assign dedicated materials. It was just left at none - maybe setting it to a proper material will work? If so I'll be sure to update the guide to reflect that.

**Comment by Souperman9** [comment]
Nope, that didn't fix it.

**Comment by Souperman9** [comment]
Oh I'm stupid, I haven't noticed the bfres presets until now somehow. I'll change that as well as the materials used on the model.

**Comment by Souperman9** [comment]
I changed the material + bfres preset, but the issues remain.

**Comment by KillzXGaming** [comment]
Do you have a working bfres so I could compare the 2? If you need to download an older build to try, you can go though the artifact page. [this](https://ci.appveyor.com/project/KillzXGaming/switch-toolbox/builds/34042121/artifacts) build is around 2 months old that might work.

**Comment by Souperman9** [comment]
[artifacts.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/5180304/artifacts.zip)

**Comment by Souperman9** [comment]
I've been importing loads of new models, and haven't encountered any artifacts - closing the issue for now.
