### ISSUE TITLE
SMD Animation Error

### ISSUE THREAD

**Issue by sebastianbrunobautes** [KillzXGaming/Switch-Toolbox#285]
because sometimes it exports the animation to smd correctly and other times it doesn't??

**Comment by sebastianbrunobautes** [comment]
it is possible to export to FBX animation??

**Comment by KillzXGaming** [comment]
Already have an issue on this. https://github.com/KillzXGaming/Switch-Toolbox/issues/264 . Nope FBX is not supported atm.
