### ISSUE TITLE
Crashes when viewing a SSBU texture

### ISSUE THREAD

**Issue by ChucklesDemKnuckles** [KillzXGaming/Switch-Toolbox#29]
So I want to get into SSBU modding but every time I try a view the texture so I can extract it, the program gives me this error ![capture](https://user-images.githubusercontent.com/46805428/51366161-13c9bd80-1ab2-11e9-85b8-df806aa79412.PNG) and then proceeds to crash, anyway I can fix. FYI I have Direct X 9 installed.

**Comment by KillzXGaming** [comment]
Make sure you have Direct X installed from [here](https://www.microsoft.com/en-us/download/details.aspx?id=35)

**Comment by techguy348** [comment]
I am having the same issue after a windows reinstall. Even if I install the directx components, I am still getting the same exact error in the picture above

**Comment by ChucklesDemKnuckles** [comment]
Yeah still doesn't work even with direct X installed

**Comment by techguy348** [comment]
https://www.youtube.com/watch?v=lisp713k38s
Noesis used in this tutorial here works as an alternative

**Comment by KillzXGaming** [comment]
I'm hoping this is now fixed. Can someone test this build? https://drive.google.com/file/d/11SjS04KYmPe1Ar84QeYunjaP09PMEbxM/view?usp=sharing
