### ISSUE TITLE
Pokemon LGPE: Bad SMD export?

### ISSUE THREAD

**Issue by sunkhaskasis** [KillzXGaming/Switch-Toolbox#296]
I'm trying to export animations from LGPE to SMD, but I'm having troubles importing them into both Blender and 3DS Max.

In Blender, I only get a single bone that doesn't do anything:
![image](https://user-images.githubusercontent.com/19194315/97063462-8f6e6d80-15a8-11eb-8a97-33b4edd2b1f1.png)

And in Max, I get a a broken skeleton which, again, doesn't do anything:
![image](https://user-images.githubusercontent.com/19194315/97063521-d78d9000-15a8-11eb-8162-b4e9f829294b.png)

Was this possibly caused by the latest update? If I'm doing some steps wrong, could you please tell me how to properly export LGPE animations?

I use Blender 2.83.5 and 3DS Max 2017, in case you need specifications.

**Comment by sunkhaskasis** [comment]
I think I have figured it out: the exported SMD contained commas instead of dots, so I quickly replaced them using a text editor and the animation worked. You may close the issue now, though I wouldn't mind to hear _why_ it happens. My locale is Russian, if that has to do with anything.

**Comment by KillzXGaming** [comment]
Some countries just use commas as decimal separators so I had to force it to use the decimal separator.
