### ISSUE TITLE
Cannot import 3D Models

### ISSUE THREAD

**Issue by TheMarioModder** [KillzXGaming/Switch-Toolbox#30]
Tried to import model, says it showed up, but doesn't appear on viewport.

**Comment by KillzXGaming** [comment]
Make sure no meshes are rigged (it'll be automatically checked with indices/weights in settings if there is). Those transform wrong atm but will be fixed in 0.9.

**Comment by KillzXGaming** [comment]
Make sure there aren't any weights/indices in the dae. That'll be an indicator if there are any. Disabling it won't fix the issue.

**Comment by KillzXGaming** [comment]
This should be fixed now
