### ISSUE TITLE
Yaml editor capitalizes bools when compiling to byml

### ISSUE THREAD

**Issue by MarioPossamato** [KillzXGaming/Switch-Toolbox#300]
Whenever I decompile a byml file to yaml format, edit it, and compile it back to byml format, it capitalizes a lowercase boolean values.  This breaks the file for anything that expects it to be lowercase in the game, because it doesn't know what to do with it.  This is unfortunate, because the yaml editor is the best of the three editors.  This fix is not of _major_ importance, but it would be nice to have it fixed at some point.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/66749710cefe61d22dc72504fe82dde68f9bc25e
