### ISSUE TITLE
Erro import .arc files

### ISSUE THREAD

**Issue by dderek** [KillzXGaming/Switch-Toolbox#31]
The .arc files are being extracted correctly, however, when we will import, even keeping standards of size and width, the game does not accept the modified files.

**Comment by dderek** [comment]
the game that was tested was the Pokemon let's go

**Comment by KillzXGaming** [comment]
Are you trying to edit a .arc from a gfpak? Since that is currently broken, will be fixed in a later update.

**Comment by dderek** [comment]
the .arc file is not originally gfpak, I can even extract the dds or even a png, however, after inserting, and putting in the game, the game closes.
I will be waiting for new updates, thank you in advance

**Comment by KillzXGaming** [comment]
Oh i see, so it's a sarc file. That may be from saving a szs in one, as sarcs in other sarcs do break, but will be fixed in the next update. Though saving the szs outside it, reopening the arc and replacing (without opening) can work for now.

**Comment by KillzXGaming** [comment]
This should be fixed now
