### ISSUE TITLE
Splatoon 2 Animations display correctly in Toolbox, but are broken in Blender

### ISSUE THREAD

**Issue by DaSpoop** [KillzXGaming/Switch-Toolbox#311]
Hi, I have an issue, every-time I try to export a Splatoon 2 Animation in any format, it exports successfully, but when I apply the Animation to the current models Armature, it begins to be buggy, and the bones are then in a completely wrong position

**Comment by KillzXGaming** [comment]
Same issue as https://github.com/KillzXGaming/Switch-Toolbox/issues/175 . DAE skeleton exports are a bit broken in blender.
