### ISSUE TITLE
The image will look weird.

### ISSUE THREAD

**Issue by gumisannnnnn** [KillzXGaming/Switch-Toolbox#313]
When I try to view the .nutexd of Taiko No Tatsujin "Drum 'n' Fun"
, it looks weird.
How can I fix it?
![tmpEDC](https://user-images.githubusercontent.com/69610236/102700233-ee8ded00-428e-11eb-8279-c760fd3a90f6.png)

**Comment by KillzXGaming** [comment]
Right click it in the tree on the left side and click the Taiko No Tatsujin fix option.
