### ISSUE TITLE
NUTEXB crash viewing mip levels on non swizzled images

### ISSUE THREAD

**Issue by gumisannnnnn** [KillzXGaming/Switch-Toolbox#314]
It crashes when I try to change the array level from 0/5 to 1/5 with Taiko no Tatsujin fix checked.

**Comment by KillzXGaming** [comment]
Need to be more specific, like what file format does this occur on? Can you give a sample file?

**Comment by gumisannnnnn** [comment]
If you do it as shown in this image, it will crash without showing any error.
[dancer_tetsuo.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/5720384/dancer_tetsuo.zip)
![image](https://user-images.githubusercontent.com/69610236/102703417-d380a480-42b1-11eb-85d3-bf95d8f06c87.png)
![image](https://user-images.githubusercontent.com/69610236/102703432-fad77180-42b1-11eb-9220-89e6c11780f1.png)

**Comment by gumisannnnnn** [comment]
Help me!!!!!

**Comment by gumisannnnnn** [comment]
Help me!!!!!!!

**Comment by KillzXGaming** [comment]
Don't expect bugs to be fixed right away. I am really busy and not very actively working on the toolbox.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/df281e645f9635e3e16d0a964a308aef2446ab89
