### ISSUE TITLE
Error importing .nutexb

### ISSUE THREAD

**Issue by ShikoruYasu** [KillzXGaming/Switch-Toolbox#32]
Getting an "attempted to divide by zero" error when trying to import a Taiko No Tatsujin "Drum 'n' Fun" .nutexb file. 
https://pastebin.com/bhSGVk9s

**Comment by KillzXGaming** [comment]
Could you attach a sample file?

**Comment by ShikoruYasu** [comment]
Yes, thank you.
They should look like character animation sheets.
Included Squid, Miku & MechaDON.

![023_spla2ika](https://user-images.githubusercontent.com/47803118/53131506-f9648300-353a-11e9-8f47-c8ef2e29b966.png)

[TaikoNUTEXB.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/2886851/TaikoNUTEXB.zip)

**Comment by KillzXGaming** [comment]
Alright It basically doesn't swizzle like smash ultimate requires, causing it to look broken or give errors. Unfortunately there's not much of a way I can determine the game it's from, but I'll try to come up with a work around
