### ISSUE TITLE
after trying to import .OBJ to make it .KCL, toolbox crashes. 

### ISSUE THREAD

**Issue by kiictus** [KillzXGaming/Switch-Toolbox#337]
when im trying to open it a with "open with...", not open.. in switch toolbox, im getting this error
![image](https://user-images.githubusercontent.com/75505346/107838461-a5e64200-6dae-11eb-90c0-dd21b255526a.png)

full error text (ask translation if needed):

Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.IO.DirectoryNotFoundException: Не удалось найти часть пути "D:\De_dust\ORIGINAL FILES\kcl\KclMaterialPresets".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileSystemEnumerableIterator`1.CommonInit()
   в System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   в System.IO.Directory.GetFiles(String path)
   в FirstPlugin.KCL.Load(Stream stream) в C:\projects\switch-toolbox\File_Format_Library\FileFormats\Collision\KCL.cs:строка 106
   в Toolbox.Library.IO.STFileLoader.SetFileFormat(IFileFormat fileFormat, String FileName, Stream stream, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat FileCompression)
   в Toolbox.Library.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, Int64 DecompressedSize, Int64 CompressedSize)
   в Toolbox.Library.IO.STFileLoader.OpenFileFormat(String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, UInt32 DecompressedSize, UInt32 CompressedSize)
   в Toolbox.MainForm.OpenFile(String FileName, Boolean InActiveEditor) в C:\projects\switch-toolbox\Toolbox\MainForm.cs:строка 279
   в Toolbox.MainForm.Form1_Load(Object sender, EventArgs e) в C:\projects\switch-toolbox\Toolbox\MainForm.cs:строка 121
   в System.Windows.Forms.Form.OnLoad(EventArgs e)
   в System.Windows.Forms.Form.OnCreateControl()
   в System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   в System.Windows.Forms.Control.CreateControl()
   в System.Windows.Forms.Control.WmShowWindow(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.Form.WmShowWindow(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Toolbox
    Версия сборки: 1.0.2356.0
    Версия Win32: 1.0.2356
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Toolbox.exe
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Toolbox.Library
    Версия сборки: 1.0.2356.0
    Версия Win32: 1.0.2356
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Toolbox.Library.DLL
----------------------------------------
Microsoft.VisualBasic
    Версия сборки: 10.0.0.0
    Версия Win32: 14.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4320.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DirectXTexNetImpl
    Версия сборки: 1.0.0.3
    Версия Win32: 
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/x64/DirectXTexNetImpl.dll
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
OpenTK
    Версия сборки: 3.0.1.0
    Версия Win32: 3.0.1
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/OpenTK.dll
----------------------------------------
Octokit
    Версия сборки: 0.31.0.0
    Версия Win32: 0.31.0.0
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Octokit.DLL
----------------------------------------
SFGraphics
    Версия сборки: 1.0.6956.42501
    Версия Win32: 1.0.6956.42501
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/SFGraphics.dll
----------------------------------------
OpenTK.GLControl
    Версия сборки: 3.0.1.0
    Версия Win32: 3.0.1
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/OpenTK.GLControl.dll
----------------------------------------
System.Net.Http
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
FirstPlugin.Plg
    Версия сборки: 1.0.2356.0
    Версия Win32: 1.0.2356
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/Plugins/FirstPlugin.Plg.dll
----------------------------------------
GL_EditorFramework
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/GL_EditorFramework.DLL
----------------------------------------
FlatBuffers
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/Plugins/FlatBuffers.DLL
----------------------------------------
Syroot.NintenTools.NSW.Bfres
    Версия сборки: 1.2.3.0
    Версия Win32: 1.2.3.0
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/Syroot.NintenTools.NSW.Bfres.dll
----------------------------------------
Syroot.Maths
    Версия сборки: 1.5.3.0
    Версия Win32: 1.5.3.0
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/Syroot.Maths.DLL
----------------------------------------
Syroot.NintenTools.Bfres
    Версия сборки: 1.2.3.0
    Версия Win32: 1.2.3.0
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/Syroot.NintenTools.Bfres.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Версия сборки: 3.0.6.0
    Версия Win32: 3.0.6.0
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/Plugins/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
Syroot.NintenTools.NSW.Bntx
    Версия сборки: 1.2.3.0
    Версия Win32: 1.2.3.0
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/Syroot.NintenTools.NSW.Bntx.dll
----------------------------------------
Syroot.BinaryData
    Версия сборки: 2.0.1.0
    Версия Win32: 2.0.1.0
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/Syroot.BinaryData.dll
----------------------------------------
SPICA
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/Plugins/SPICA.DLL
----------------------------------------
ZeldaLib
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/Plugins/ZeldaLib.DLL
----------------------------------------
System.Numerics
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Версия сборки: 0.0.0.0
    Версия Win32: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
KclLibrary
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/KclLibrary.dll
----------------------------------------
KclLibraryGUI
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Users/timav/Desktop/TRULY%20DESKTOP/SW%20toolbox/Lib/KclLibraryGUI.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.

**Comment by KillzXGaming** [comment]
Are you using the latest build? The more recent updates should fix this.

**Comment by kiictus** [comment]
Gonna try it, thanks. Also does new build fixes "zNear" error?

**Comment by kiictus** [comment]
nope, still crashes.

**Comment by kiictus** [comment]
I tried wexos toolbox, but I got error too. That means .OBJ is wrong exported. My bad, sorry.
