### ISSUE TITLE
BNTX file corrupts on save due to improper alignment

### ISSUE THREAD

**Issue by dderek** [KillzXGaming/Switch-Toolbox#34]
is no longer possible to open .arc files, when I talked about this type of format, not referring to .sarc files and yes .arc files, after updating the plugins, there is no longer support for this type of file.

I'm attaching the file so you can do tests, okay?

[title_v_00_eng.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/3000621/title_v_00_eng.zip)

**Comment by dderek** [comment]
inside the .arc file has a folder with name timg, inside this folder has a file called _Combined.bntx, inside that file, there are image files .... and about them that I have been talking about. until it is possible to extract, but impossible to put again without corrupting

**Comment by GRAnimated** [comment]
3DS, Wii U, and Switch arcs are usually SARCs.

**Comment by KillzXGaming** [comment]
Seems it's not an arc issue but more of a BNTX one where it fails to save. If a bntx contains user data, it seems to not save properly, i'll be sure to fix that

**Comment by KillzXGaming** [comment]
Alright should be fixed now on the current commit
