### ISSUE TITLE
saving does not work its always grayed out so I never can save

### ISSUE THREAD

**Issue by BeegAssYoshi** [KillzXGaming/Switch-Toolbox#340]
please help me :c

**Comment by andercard0** [comment]
> please help me :c

could you please reach us on discord so we can help you properly ?

**Comment by BeegAssYoshi** [comment]
> > please help me :c
> 
> could you please reach us on discord so we can help youYes!,

**Comment by BeegAssYoshi** [comment]
> > please help me :c
> 
> could you please reach us on discord so we can help you properly ?

yes ur discord is?
