### ISSUE TITLE
skeletal animation not exporting correctly (preferably to .smd) (wii u .szs)?

### ISSUE THREAD

**Issue by nipapi14** [KillzXGaming/Switch-Toolbox#348]
It might be an exceptional case, but I'm trying to export an animation from toolbox of an .szs file from the original splatoon on the wii u, but importing just the animation into blender, not the model, doesn't display the animation properly, yet it plays perfectly in toolbox.
I'm trying to export the animation so i can see the general positions and rotations of one model that was duplicated multiple times. It's a common thing they like to do in that game.
Specifically, I'm trying with the model linked. The animation that I'm specifically trying to export is Fld_Ruins00_DV_Plant_auto, although it appears all the animations when exported don't work at all when imported into blender, and I'm just talking the rig, I'm not even talking about the meshes themselves here.
I've tried exporting it as .smd and .seanim but it doesn't appear to make a difference. .smd is preferred.

https://www.mediafire.com/file/y6323zxowbfutwv/Fld_Ruins00.rar/file

**Comment by Jenrikku** [comment]
Probably a Blender error not Toolbox's. Tried with SM3DW anims and same happens, it kinda works better if you convert the dae to an fbx... But still has errors.

**Comment by nipapi14** [comment]
but you can't export the anim to a dae. I'm not talking about the meshes, I'm talking about the rig of the skeleton itself. All of the bones force themselves to the centre and don't animate. Animations from splatoon 2 work and imported fbx's can pull over them perfectly, but the animation itself doesn't export properly from toolbox in the first place

**Comment by nipapi14** [comment]
not to mention, viewing the smd in a hex editor also reveals that all the bones are incorrectly assigned and given no values for animating. Just straight up 360 frames of no data, in the smd format. That doesn't sound like it isn't a toolbox issue to me, that's just from toolbox itself.

**Comment by Jenrikku** [comment]
You can edit the smd with any text editor like notepad as It's just special text.

**Comment by nipapi14** [comment]
yes but for 360 frames of unknown that's not exactly a viable solution. Should export at least in the first place with data. Doesn't matter what editor you view it in everything is set to 0 so there's nothing to animate. Should be fixed.

**Comment by bobesponjawow** [comment]
Had the same issue, a workaround I had to do was to import the SMD animation files to 3DS Max and then export it from 3DS Max as SMD to Blender. Only issue is that SMD importer doesn't work on latest version of 3ds max, so you need to subscribe to get an older version and subscription to it is really expensive.

**Comment by nipapi14** [comment]
I had seen that. And by latest version I'm not sure what you mean. 2017's a long time ago and that's the version I have. Said smd importer didn't work on the files.

Especially because the smd file in the first place had incorrect skeleton names when exported. A plant's bone names with the word boat in them? Bit strange.

it was fixed in a later compile though thankfully
