### ISSUE TITLE
Extracting shader data to material?

### ISSUE THREAD

**Issue by DaSpoop** [KillzXGaming/Switch-Toolbox#352]
Hi, I would like to ask if extracting shader data from a model to a material file Blender can read and open is possible?
I know it is not just want to make sure... you know recreating shaders takes ages.....

**Comment by KillzXGaming** [comment]
Recreating them would be more ideal that using ripping shaders. Shaders per game have to have all the data understood so you know what data gets passed to each block, samplers used (there are hardcoded textures typically like shadows and cubemaps) and there are other various factors like needed shader attributes, limiting variation data (like skin count), it would just be too difficult to get working in a practical way.
