### ISSUE TITLE
Imported Materials/Objects have no name

### ISSUE THREAD

**Issue by ShrineFox** [KillzXGaming/Switch-Toolbox#36]
When importing a new material or object for a model, the name is blank by default. In the case of materials, changing the Name field on the right pane does not update the name.

Right clicking the material or object and choosing Rename still works in both cases though.

**Comment by KillzXGaming** [comment]
Fixed in https://github.com/KillzXGaming/Switch-Toolbox/commit/211326d25386ff7005aa640c687284526ad2a85d
