### ISSUE TITLE
szs file not opening

### ISSUE THREAD

**Issue by JaySpinjitzu** [KillzXGaming/Switch-Toolbox#369]
So I was working on a custom level for sm3dw + bf, but I had to restart my pc, and now toolbox won't open it. some other .szs files seem to open but not all.

**Comment by mjcox244** [comment]
is it opening fine in spotlight?

**Comment by MonsterDruide1** [comment]
Which exact file were you trying to open? Did you save the file in-between? If it's not too far progressed, maybe try again on a fresh file.

**Comment by JaySpinjitzu** [comment]
Oh dang this is old all good now

**Comment by MonsterDruide1** [comment]
Okay, then please close this issue if you don't need any help in this case anymore.
