### ISSUE TITLE
Can't it replace .bfres file in NSP file?

### ISSUE THREAD

**Issue by JoneHermer** [KillzXGaming/Switch-Toolbox#370]
> [
![Untitled](https://user-images.githubusercontent.com/42021855/120583981-57da7480-c459-11eb-9df4-9d5b3f325ed3.png)
](url)
Can it replace .bfres file on that NSP file? I can't replace that .bfres file, I just wanna change texture on that file, please help. Thanks.
Game: Kirby Star Allies

**Comment by MonsterDruide1** [comment]
It looks like that isn't a real `.bfres` file... it's filename suggests it's some different format (`.bfres.cmp`). Are you sure that this file is of the standard `bfres` format? Check that by extracting the `Raw Data`, then open it in a Hex Editor to check the first few bytes.

**Comment by JoneHermer** [comment]
Can you show me a hex to edit? I don't know about editing hex. Thanks.

**Comment by MonsterDruide1** [comment]
Just check for a hex editor (like `HxD`) and open the raw data with that program. The first few bytes will indicate the real file format.
