### ISSUE TITLE
Save or Rebuild .NSP file and .XCI file

### ISSUE THREAD

**Issue by JoneHermer** [KillzXGaming/Switch-Toolbox#372]
Hi, can Switch Toolbox have a rebuild or save? I can't save the rom even I've edited the the file (.bfres) in .NSP (or .XCI)
I just want to edit the texture. Can anyone help? Thanks.
![Untitled](https://user-images.githubusercontent.com/42021855/120771776-ceef3600-c549-11eb-96c3-f6cf6d857e73.png)

**Comment by Demonslayerx8** [comment]
You don't really need to edit the nsp/xci of the game, just extract the romfs files, edit the textures u want, and put it in the proper category for loading mods.

**Comment by JoneHermer** [comment]
Can it use for emulator?

**Comment by Demonslayerx8** [comment]
yeah, altho I'm not a emulator person, so I can't help ya there in how to load modded files in it.

**Comment by MonsterDruide1** [comment]
I agree: Re-packaging the `NSP`/`XCI` is not neccessary, you can use the edited file in emulators/console just fine. If you'd really want to do it anyways, check out this project: https://gbatemp.net/threads/hacpack-build-and-repack-ncas-and-nsps.519815/

Normally, you extract the RomFS/ExeFS using `hactool`, but that doesn't support recompressing of the edited ROM. Instead, you have to use other tools like the one above.

**Comment by MonsterDruide1** [comment]
If those comments solved your problem, feel free to close this issue ; otherwise just ask again.

**Comment by JoneHermer** [comment]
Do you have tutorial of Hacpack? i don't know how to use it. Thanks!

**Comment by MonsterDruide1** [comment]
Check here: https://github.com/The-4n/hacPack/tree/master/docs
