### ISSUE TITLE
Why i cannot import pngs?

### ISSUE THREAD

**Issue by ZokemonLP** [KillzXGaming/Switch-Toolbox#374]
hello, i want to make a texture swap. but when i want to replace the png the replace button is grey and i cannot click on it. why is it so?
![Screenshot (22)](https://user-images.githubusercontent.com/84643484/121557300-ee3c0680-ca14-11eb-97d5-25ac5e6fb486.png)

**Comment by KillzXGaming** [comment]
If a feature is grayed out, it is not supported. There are no plans for editing LM2/LM3 dict format atm due to being too complicated and lack of proper research.
