### ISSUE TITLE
Drag&Drop Feature (Re)Added?

### ISSUE THREAD

**Issue by DaSpoop** [KillzXGaming/Switch-Toolbox#379]
Hi, I am a long time Switch Toolbox user, but there is one thing I think got removed, but i don't know why, I always used to Drag&Drop whatever files I needed to the program, but it's not here now, can you please add it back, or if it is my problem, tell me how to fix it?

**Comment by KillzXGaming** [comment]
Make sure the tool is not running as admin. It's a windows thing where you cannot drag/drop in applications as admin due to some security thing.

**Comment by DaSpoop** [comment]
Oh, thank you, that fixed my issue!
