### ISSUE TITLE
(REQUEST) Wario World support?

### ISSUE THREAD

**Issue by SonikkuA-DatH** [KillzXGaming/Switch-Toolbox#388]
I noticed Luigi's Mansion had support despite being a tough format on GC, so I wonder if Wario World (by Treasure) can get support for its RSC Archives/Models? Reynol2 has made an extractor for the archives here: https://github.com/RenolY2/warioRSC

**Comment by KillzXGaming** [comment]
It is supported in this tool including models and skeletal animations.  https://github.com/KillzXGaming/Toolbox.Reborn/releases
