### ISSUE TITLE
Unable to Import/Replace Skeleton

### ISSUE THREAD

**Issue by ShrineFox** [KillzXGaming/Switch-Toolbox#39]
When exporting a .bfskl from one model and replacing with it in another, nothing appears to happen. Same thing happens when you use Replace on the Model itself with a FBX or DAE-- the old skeleton seems to be retained still. Clearing all bones also does not appear to be permanent (despite the warning).

Tested with the following files:
Link.bfskl (exported from TitleBG.pack/Model/Link.bfres)
Npc_Zora_Hero.bfres (from Content/Model/)

**Comment by KillzXGaming** [comment]
The original skeleton will always stay for a .dae unless you check the import bones option in the settings. It'll also automatically use a single bone if none are found as every model has a bone, rigged or not.

**Comment by ShrineFox** [comment]
Thanks, I totally missed the Import Bones checkbox. Still not sure why replacing one skeleton with another directly doesn't work. Is it unimplemented?

**Comment by KillzXGaming** [comment]
Apparently yeah i must've forgot to overwrite the replace function. I'll be sure to fix it in an hour or so.

**Comment by KillzXGaming** [comment]
Alright should be fine now
