### ISSUE TITLE
Can't scale or move object in model .fmdb file

### ISSUE THREAD

**Issue by JoneHermer** [KillzXGaming/Switch-Toolbox#391]
Hi, I just want to move some object and scale it bigger and smaller. But it's not work, I try to change value to 10.000000 but it's not happened. Did I missed something? Please help! Thanks.
![Untitled](https://user-images.githubusercontent.com/42021855/130361599-67562660-b066-4cfc-8c57-fbf8505c73cb.jpg)

**Comment by KillzXGaming** [comment]
The UI isn't functional. You should transform in other tools like blender.
