### ISSUE TITLE
Source code of some libraries

### ISSUE THREAD

**Issue by nnn1590** [KillzXGaming/Switch-Toolbox#394]
This project uses libraries starting with `Syroot.NintenTools.NSW` and a library named `ZeldaLib`, where is the source code for these?
I tried looking on GitHub and [Syroot's GitLab](https://gitlab.com/groups/Syroot/NintenTools/-/archived), but I couldn't find them.

**Comment by jupahe64** [comment]
Syroot.Nintentools.NSW is part of the BfresLibrary repo

there was a commit that changed all namespaces to BfresLibrary though so you might need to download the repo before that commit

**Comment by nnn1590** [comment]
Thank you!

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
Since this issue is resolved, it should be closed

**Comment by Trinsid** [comment]
@KillzXGaming hey man me and some other friends miss you, get back on Discord

**Comment by nnn1590** [comment]
Umm… I'm very sorry, but I haven't found the source yet.
I looked at the commit [Simply namespace to just "BfresLibrary"](https://github.com/KillzXGaming/BfresLibrary/commit/759217765db29bf36a129e05c90c7c74eb778daa#diff-2d3622f9bf8eb84d25ff4e3828136043eccd893694142ccd2d3a5b3013d5e3ff) and [the source tree before it](https://github.com/KillzXGaming/BfresLibrary/tree/5b46eb22b2237797ed9c97a19df009d0e95aca3a).
But even from there I could not find the source for `NSW.Bntx` (e.g. `ChannelType` definition)
However, I could see that [it depended on the binary `Syroot.NintenTools.NSW.Bntx.dll`](https://github.com/KillzXGaming/BfresLibrary/tree/5b46eb22b2237797ed9c97a19df009d0e95aca3a/Libraries).

**Comment by KillzXGaming** [comment]
They can be found here https://github.com/KillzXGaming/LegacySwitchLibraries

**Comment by nnn1590** [comment]
Oh, thank you very much!
