### ISSUE TITLE
Can this tools edit the main file in exefs folder?

### ISSUE THREAD

**Issue by zellfy** [KillzXGaming/Switch-Toolbox#40]
which type is nso.

**Comment by OcelotGamingDev** [comment]
No, it can't edit the main file in exefs folders, to edit those use a tool like [IDA](https://www.hex-rays.com/products/ida/) to look at the contents of the file (assembly code), and then use something like [IPSwitch](https://github.com/3096/ipswitch) to run the patches that you make.

**Comment by KillzXGaming** [comment]
I don't plan on exefs edits. This is for romfs editing file formats for Switch and Wii U games atm. Though anyone is free to add such tools or whatever to this if they feel the want to.
