### ISSUE TITLE
I Cant Load Texture Files In Switch Toolbox

### ISSUE THREAD

**Issue by NeckGod00** [KillzXGaming/Switch-Toolbox#406]
So every time I launch switch toolbox, and yes its the latest version, I cant seem to load .nutexb files. It shows a loading sign and the texture never pops up. My question is what could the problem be? I downloaded everything right so could yall help me out? Another important thing to note is that this error message pops up every time I launch switch toolbox: _Systm.IO.FileNotFoundException: Could not load file or assembly 'DirectXTexNetImpl.dll" or one of it's dependencies. The specified module could not be found. File name: 'DirectXTexNetImpl.dll' at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence) at System.Reflection.Assembly.LoadFile(String path) at Toolbox.Program.TryLoadDirectTex() in C:\projects\switch-toolbox-fkj3m\Toolbox\Program.cs:line 151_

**Comment by NeckGod00** [comment]
Thank you this helped

**Comment by ThoseThings** [comment]
I installed the files, but I don't know what to do with them...
