### ISSUE TITLE
How to extract bntx from bffnt?

### ISSUE THREAD

**Issue by masagrator** [KillzXGaming/Switch-Toolbox#41]
I'm trying to use the newest version to extract bntx file from Zelda BOTW bffnt file. 
When i try to just open it, it shows nothing. Extract BNTX - nothing.
Old version shows for two seconds in task manager and disappears. Even with runned as admin. 
Am I doing something wrong?

Windows 10 Pro x64 1809. .NET Framework 4.6.2 installed. 
Old version unpacked after unlocking.

**Comment by KillzXGaming** [comment]
Try the latest one. Should open fine

**Comment by masagrator** [comment]
After restarting PC it worked. Huh.
