### ISSUE TITLE
Opening NCA file does nothing; Edit button on menu bar turns gray

### ISSUE THREAD

**Issue by VideoGamePlayer7** [KillzXGaming/Switch-Toolbox#42]
I opened up a .NCA file, but nothing happened when I opened it, except the Edit button on the menu bar became unclickable. Can someone help me?

**Comment by masagrator** [comment]
In README there is nothing mentioned about NCA.

**Comment by KillzXGaming** [comment]
Keep in mind it's still pretty experimental. I haven't added support for the format and haven't removed the extension to the list since I was planning on supporting it but haven't gotten around to it
