### ISSUE TITLE
SZS cannot save

### ISSUE THREAD

**Issue by VoviTekk** [KillzXGaming/Switch-Toolbox#420]
hi me again. i can't save szs files, i mean the wii format. is the szs format different or something like that? 
![image](https://user-images.githubusercontent.com/65232880/140556989-e64b1539-44f8-4857-b535-c8525e039f2d.png)

**Comment by datkat21** [comment]
Having the same problem, did you find any solution?

**Comment by datkat21** [comment]
Found a workaround, extract the root (`.`) folder after you've modified it and then re-pack it using wszst. Or just extract the szs beforehand (but then you'll lack the textures)
