### ISSUE TITLE
Can't Access a Closed File?

### ISSUE THREAD

**Issue by ROGsamurai** [KillzXGaming/Switch-Toolbox#424]
trying to open sounds from Super Mario 3D All Star
![ttttt](https://user-images.githubusercontent.com/94874077/142946030-fddc80d5-9714-4df4-93df-846c4b8ad92c.png)
s

**Comment by KillzXGaming** [comment]
Same issue as https://github.com/KillzXGaming/Switch-Toolbox/issues/208 . Version is newer and not supported atm.
