### ISSUE TITLE
Pokémon Legends Arceus .gfpak file support

### ISSUE THREAD

**Issue by Andree12** [KillzXGaming/Switch-Toolbox#438]
Switch Toolbox ​can't open up .gfpak files from **Pokémon Legends Arceus** 

It is similar to Sword and Shield's .gfpak files but Legends Arceus' .gfpak files are likely compressed.

**Comment by jugolm** [comment]
Weirdly enough I had an old version of the Toolbox and I managed to see the content of GFPAK files, but I made the mistake of pressing update and now it crashes when trying to read. (Read value 3 is not defined in the given enum type)

**Comment by Andree12** [comment]
It works as of January 20th, 2022 but currently, we can't read the files in Pokémon Legends Arceus' .gfpak files now.

**Comment by KillzXGaming** [comment]
Since the game isn't out yet I'd prefer for leaked stuff to not have files sent here. 

There is a PR for fixing this  https://github.com/KillzXGaming/Switch-Toolbox/pull/440 .

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/55b9969a8e253a5754ee876ddc8aa74c993a7f41
