### ISSUE TITLE
Wut

### ISSUE THREAD

**Issue by 0x3770** [KillzXGaming/Switch-Toolbox#446]
![image](https://user-images.githubusercontent.com/93094011/151946369-cff5101e-3b41-40f5-8530-68da34b55241.png)

**Comment by 0x3770** [comment]
fixed by downloading DDL and putting in build DIR
but opening models folder fails in Pokémon Legends: Arceus
![image](https://user-images.githubusercontent.com/93094011/151947034-7969faf2-a9ce-4789-bb73-9b8c695d4ec4.png)

**Comment by Funnyshii** [comment]
> fixed by downloading DDL and putting in build DIR but opening models folder fails in Pokémon Legends: Arceus ![image](https://user-images.githubusercontent.com/93094011/151947034-7969faf2-a9ce-4789-bb73-9b8c695d4ec4.png) Issue with gfbmdl.cs

did you figured it out how to solve the models problem?
