### ISSUE TITLE
Text editor not actually editing text

### ISSUE THREAD

**Issue by MegAmi24** [KillzXGaming/Switch-Toolbox#456]
I'm trying to edit one of the WMBT files in WarioWare: Get It Together, however it seems the text editor isn't applying my changes. When typing in the "Edit:" text box, it seems to work fine, however the hex view never changes, and clicking on another text string and going back to the one I edited reverts it back to the original.
![image](https://user-images.githubusercontent.com/7158344/153722969-15701d37-6927-48c0-a918-c5642f78b46d.png)

I tested an MSBT file from 3D World + Bowser's Fury, and the same thing is happening there:
![image](https://user-images.githubusercontent.com/7158344/153722998-38393aef-12b1-4eed-a390-e67335f6a588.png)

As you'd expect, clicking the Save button does not save my edits. I'm using the latest version downloaded through the updater.

**Comment by KillzXGaming** [comment]
MSBT does not support saving. Dupe of https://github.com/KillzXGaming/Switch-Toolbox/issues/310

**Comment by MegAmi24** [comment]
Why is there a save button then?

**Comment by KillzXGaming** [comment]
Every format has a save button. Grayed out means saving isn't possible. For the most part editing worked on simple files but there are some that currently break so it isn't enabled atm.

**Comment by Fusseldieb** [comment]
Issue still exists @KillzXGaming 

Not being able to save .wmbt and msbt is a dealbraker imo
