### ISSUE TITLE
Error trying to open models folder in Pokemon Legends: Arceus

### ISSUE THREAD

**Issue by Funnyshii** [KillzXGaming/Switch-Toolbox#462]
when i try to open the models folder this happens

![image](https://user-images.githubusercontent.com/75316566/156059241-6082d9bd-3499-43ba-9eec-47b832c8d723.png)

also when i try to export some pokemon textures, some don't have the whole texture like some files are missing

**Comment by KillzXGaming** [comment]
Models are not supported atm and textures aren't missing, they are colored by materials.
