### ISSUE TITLE
animal crossing new horizons crash

### ISSUE THREAD

**Issue by Pokimail** [KillzXGaming/Switch-Toolbox#474]
when applying the modifications and compressing the .sarc.zs files the game crashes and does not start. and when replacing the file the manager does not find the file because the program adds more text to the original file that was modified.

**Comment by Bellzine** [comment]
I may be able to help you with this as I've done a lot of model edits and replacements and I doubt it's an issue with Toolbox specifically, if it is then I'd like to know to work around it. Could you give a more detailed explanation of what you're doing and your steps, including what you add/delete from the .zs?

**Comment by Pokimail** [comment]
I perform the edit in kimiru hex editor replacing words and respecting spaces, paragraphs and special programming characters and saving with required compression. when replacing the files in the tool box when looking in the manager where some are it opens normally others it does not find if I click on them and replace they break when compressing, they only find when the manager finds them with another name example: nome.zs(original ) it only opens as:name_name.zs and even then it either breaks or not. it's like the program is bored of compressing, lol

**Comment by KillzXGaming** [comment]
ACNH has a RSTB file table so that file either needs to be blanked out (will cause potential lag in game) or adjusted (though idk if there are current tools that work with it).

**Comment by Pokimail** [comment]
great information, thank you very much and for your attention, so far my translation does not face this type of problem.  only files with more than 10 lines translated damage the file completely, I don't know why.

**Comment by Fusseldieb** [comment]
Maybe this does help: https://github.com/zeldamods/rstb

It is for BOTW, however, might be a starting point
