### ISSUE TITLE
Trying to convert to Little Endian

### ISSUE THREAD

**Issue by camboozle** [KillzXGaming/Switch-Toolbox#475]
Im trying to port a Mario Kart 8 mod over to Deluxe, but it wont allow me to convert the szs file, as i get this message.
![image](https://user-images.githubusercontent.com/102335295/160033254-cbad38fc-78d6-4f21-ae6c-a2dc2eae9aae.png)
The crash details are as follows:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Header mismatch
   at ByamlExt.Byaml.ByamlFile.Read(Stream stream, Encoding encoding, Boolean leaveOpen)
   at ByamlExt.Byaml.ByamlFile.LoadN(Stream stream, Boolean supportPaths, ByteOrder byteOrder, Boolean leaveOpen)
   at FirstPlugin.BYAML.Load(Stream stream) in C:\projects\switch-toolbox\File_Format_Library\FileFormats\Byaml\BYAML.cs:line 239
   at FirstPlugin.BYAML.MenuExt.ConvertBEtoLE(Object sender, EventArgs args) in C:\projects\switch-toolbox\File_Format_Library\FileFormats\Byaml\BYAML.cs:line 165
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Toolbox
    Assembly Version: 1.0.2517.0
    Win32 Version: 1.0.2517
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Toolbox.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Toolbox.Library
    Assembly Version: 1.0.2517.0
    Win32 Version: 1.0.2517
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Toolbox.Library.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DirectXTexNetImpl
    Assembly Version: 1.0.0.3
    Win32 Version: 
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/x64/DirectXTexNetImpl.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
OpenTK
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/OpenTK.dll
----------------------------------------
Octokit
    Assembly Version: 0.31.0.0
    Win32 Version: 0.31.0.0
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Octokit.DLL
----------------------------------------
SFGraphics
    Assembly Version: 1.0.6956.42501
    Win32 Version: 1.0.6956.42501
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/SFGraphics.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/OpenTK.GLControl.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
FirstPlugin.Plg
    Assembly Version: 1.0.2517.0
    Win32 Version: 1.0.2517
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/Plugins/FirstPlugin.Plg.dll
----------------------------------------
GL_EditorFramework
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/GL_EditorFramework.DLL
----------------------------------------
FlatBuffers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/Plugins/FlatBuffers.DLL
----------------------------------------
Syroot.NintenTools.NSW.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/Syroot.NintenTools.NSW.Bfres.dll
----------------------------------------
Syroot.Maths
    Assembly Version: 1.5.3.0
    Win32 Version: 1.5.3.0
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/Syroot.Maths.DLL
----------------------------------------
Syroot.NintenTools.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/Syroot.NintenTools.Bfres.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/Plugins/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.1.22727
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/Newtonsoft.Json.dll
----------------------------------------
Syroot.NintenTools.NSW.Bntx
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/Syroot.NintenTools.NSW.Bntx.dll
----------------------------------------
Syroot.BinaryData
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/Syroot.BinaryData.dll
----------------------------------------
SPICA
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/Plugins/SPICA.DLL
----------------------------------------
ZeldaLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/Plugins/ZeldaLib.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
OptaneShellExt
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/WINDOWS/System32/DriverStore/FileRepository/iastorpinningcomponent.inf_amd64_b31ddd6f2a24807e/OptaneShellExt.dll
----------------------------------------
SharpShell
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.0
    CodeBase: file:///C:/WINDOWS/System32/DriverStore/FileRepository/iastorpinningcomponent.inf_amd64_b31ddd6f2a24807e/SharpShell.DLL
----------------------------------------
PinningServiceApi
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/WINDOWS/System32/DriverStore/FileRepository/iastorpinningcomponent.inf_amd64_b31ddd6f2a24807e/PinningServiceApi.DLL
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
SARCExt
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/SARCExt.dll
----------------------------------------
DirectXTexNet
    Assembly Version: 1.0.0.3
    Win32 Version: 1.0.0.3
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/DirectXTexNet.DLL
----------------------------------------
ByamlExt
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Users/camer/Desktop/Switch%20Tools/Switch%20Toolbox/Lib/ByamlExt.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by KillzXGaming** [comment]
You cannot convert the .szs (model) with the byaml converter nor can you auto convert it. Need to redo the importing process to port over course models.
