### ISSUE TITLE
Issue with NokonokoNpc.bfres

### ISSUE THREAD

**Issue by Yoshimaster96** [KillzXGaming/Switch-Toolbox#48]
I tried to rip the model file `NokonokoNpc.bfres`, found inside `NokonokoNpc.szs` in the `ObjectData` folder in Super Mario Odyssey, but for some reason not all the bones get exported properly:
![Capture97](https://user-images.githubusercontent.com/15160568/56102969-e4322200-5ef5-11e9-9d17-65fde8a9d777.PNG)

I built the latest commit (as of 9 April 2019) in Visual Studio, and exported to DAE using that.

**Comment by KillzXGaming** [comment]
That's strange. I suppose they are not all there under jointRoot, the one that has the bone icons?

**Comment by KillzXGaming** [comment]
Well i tried it myself and it exports fine with all bones on the latest. Can you try the latest one? It's on the releases page (it automatically will build on every commit that's successful)
