### ISSUE TITLE
CoursePict doesnt change in game

### ISSUE THREAD

**Issue by vos6434** [KillzXGaming/Switch-Toolbox#480]
I've changed the image of ym_CoursePict_DLC07_00_u.bntx and saved it, I've double checked its saved but when I apply the mod, it doesn't change in game.

**Comment by KillzXGaming** [comment]
Make sure you have a ^ in the file name like ym_CoursePict_DLC07_00^u.bntx. It's currently an issue with the way illegal characters are handled from System.IO.Path.GetInvalidFileNameChars() atm since it marks some which aren't invalid in windows.

**Comment by KillzXGaming** [comment]
This was the result of an exporting bug which should be fixed in the current build https://github.com/KillzXGaming/Switch-Toolbox/commit/196a7f552565de5a80c4e8aa0dadb8e99e187b19
