### ISSUE TITLE
Corrupted normal maps and specular maps in Wii U bfres.

### ISSUE THREAD

**Issue by mg76Aniimations** [KillzXGaming/Switch-Toolbox#49]
When imported into a Wii U bfres, the normal maps and specular maps seems to corrupt. Sometimes, it's totally broken in in the tool box and in game, and other times, it properly shows up in tool box but is corrupted in game.

https://media.discordapp.net/attachments/411433841417519104/567617538385772544/unknown.png?width=576&height=571

**Comment by KillzXGaming** [comment]
Can you send an example image that has the issue?

**Comment by KillzXGaming** [comment]
Should be working on the latest now

**Comment by KillzXGaming** [comment]
I presume this is fixed now BOTW seems to be working fine, and swizzling was just glitching up. Feel free to reopen if the issue persists.
