### ISSUE TITLE
switch toolbox does not recognize cbntx and cbfmd files

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [KillzXGaming/Switch-Toolbox#496]
i remember they just loaded in older versions

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
potentially a narc issue since they were inside a narc file

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
it is a NARC issue, the hex viewer is showing something completely wrong

**Comment by KillzXGaming** [comment]
Probably just compressed as the libraries was changed. Would like a sample file to test it.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
[Gotcha](https://drive.google.com/file/d/1vZRShCyGmVo-DcsR5oKwzlG_2-AMAbV9/view?usp=sharing)

**Comment by KillzXGaming** [comment]
Sorry, should be more specific. I need a .narc sample/

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
that link is now to the narc file

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
can you check it out?

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/28f269c2d933720cdeef40465f03d524fd79de20
