### ISSUE TITLE
DirectXTexNetImpl missing when zip is extracted on PC.

### ISSUE THREAD

**Issue by PandaHexCode** [KillzXGaming/Switch-Toolbox#50]
crash: System.TypeInitializationException: Der Typeninitialisierer für "DirectXTexNet.TexHelper" hat eine Ausnahme verursacht. ---> System.IO.FileNotFoundException: Die Datei oder Assembly "DirectXTexNetImpl.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Das angegebene Modul wurde nicht gefunden.
   bei System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   bei System.Reflection.Assembly.LoadFile(String path)
   bei DirectXTexNet.TexHelper..cctor() in C:\Users\Nathan\Documents\GitHub\Switch_Toolbox\DirectXTexNet-master\DirectXTexNet\DirectXTexNet.cs:Zeile 1126.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Switch_Toolbox.Library.DDSCompressor.DecompressBlock(Byte[] data, Int32 width, Int32 height, DXGI_FORMAT format)
   bei Switch_Toolbox.Library.STGenericTexture.DecodeBlock(Byte[] data, UInt32 Width, UInt32 Height, TEX_FORMAT Format)
   bei Switch_Toolbox.Library.STGenericTexture.GetBitmap(Int32 ArrayLevel, Int32 MipLevel)

**Comment by KillzXGaming** [comment]
Make sure you unblock the zip and that the dlls in \Lib\x64 and \Lib\x86 are not missing

**Comment by PandaHexCode** [comment]
and what do I do if they are missing
Can we talk on discord?
