### ISSUE TITLE
Splatoon 3 Splatfest World Premiere .zs issues

### ISSUE THREAD

**Issue by zy0tek** [KillzXGaming/Switch-Toolbox#503]
When opening any .zs file, the file structure appears to be intact, but only particular files appear to contain data extractable with toolbox. 
Trying a batch export gave me "an invalid signature, expected 'fbvs' but got 'fska' "

**Comment by UntitledOutput** [comment]
It's being fixed right now.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/af0869d308b1d2cfe985c381996269511afe86be
