### ISSUE TITLE
File will not 

### ISSUE THREAD

**Issue by micpic1234** [KillzXGaming/Switch-Toolbox#505]
![image](https://user-images.githubusercontent.com/112180631/186911318-3a221a29-09eb-4529-95b5-e864016f6b4f.png)

Keep getting this error message when both importing and/or replacing texture files; just started yesterday. File will not open after saving new version.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/9ca9703a2318acf7dfe00f895c436f1463c4bc2a
