### ISSUE TITLE
Splatoon 3 Bfres v10

### ISSUE THREAD

**Issue by EmmyOcelotO-O** [KillzXGaming/Switch-Toolbox#506]
Upon saving a Splatoon 3 bfres file, an error states that v10 bfres files cannot be saved yet.
![Capture](https://user-images.githubusercontent.com/112229589/187013357-1500e2b7-0027-4761-bd7c-e016e96bdac3.PNG)
.

**Comment by Hedwig7s** [comment]
Because you can't save them yet

That's intentional until exporting is supported

**Comment by EmmyOcelotO-O** [comment]
Ah, I see. Fair enough then. Well, hopefully it can be done in the near future.

**Comment by Hedwig7s** [comment]
> Ah, I see. Fair enough then. Well, hopefully it can be done in the near future.

Actually it is possible with the [latest commit](https://ci.appveyor.com/api/buildjobs/vd8d70secwgdt4yw/artifacts/Toolbox-Latest.zip) but the scaling is broken

**Comment by EmmyOcelotO-O** [comment]
Noted. I’ll have to take a look this and perhaps just wait a few days for the kinks to be worked out.

**Comment by KillzXGaming** [comment]
Only possible to save .bfres without models atm. The material structure is too different and there aren't any plans to support fully loading/saving it atm.

**Comment by Hedwig7s** [comment]
> Only possible to save .bfres without models atm. The material structure is too different and there aren't any plans to support fully loading/saving it atm.

Well model saving seems to work so that's nice

Is there a reason this happens tho?
<img width="440" alt="image" src="https://user-images.githubusercontent.com/51961150/187304414-9cb6ddfc-d3df-47df-8fe0-ba08253c26a5.png">

**Comment by KillzXGaming** [comment]
What is the issue?

**Comment by Hedwig7s** [comment]
> What is the issue?

The scale is completely different

**Comment by KillzXGaming** [comment]
Yeah but what are you comparing with? Another player model file?

**Comment by Hedwig7s** [comment]
Both Inkling Female

**Comment by EmmyOcelotO-O** [comment]
Doesn’t Splatoon 2 use v8 though? They may have changed how things are formatted from then.

**Comment by Hedwig7s** [comment]
> Doesn’t Splatoon 2 use v8 though? They may have changed how things are formatted from then.

Still not fun having to deal with that
Hard to compare the size of both characters if the scale is different so just resizing it wrong will make it different

**Comment by EmmyOcelotO-O** [comment]
I agree. As Nintendo continues to develop Splatoon 3, more and more models, textures and such are going to use v10. It’s only a matter of when they do, not if. Hopefully the scaling and texture issues can be resolved but I understand that it’s not a priority.

**Comment by KillzXGaming** [comment]
Well Splatoon 3 has a very different physics engine and probably has a different scale, probably not an issue with tool.

**Comment by EmmyOcelotO-O** [comment]
There are notable changes from the second game, but how much did the core physics engine change? I mean, they really didn’t need to reinvent the wheel with the 3rd game.

**Comment by KillzXGaming** [comment]
It seems to be a physics engine called Phive used in house by other Nintendo EPD games and Splatoon 3 just is updated to use that current engine.

**Comment by EmmyOcelotO-O** [comment]
2 things:

1. That could explain the scaling issue if they changed unit measurements for their environments.
2. What does EPD mean specifically in this context?

**Comment by KillzXGaming** [comment]
EPD is a specific team of Nintendo https://en.wikipedia.org/wiki/Nintendo_Entertainment_Planning_%26_Development

**Comment by EmmyOcelotO-O** [comment]
Ah, thank you for explaining it. Thanks again for sharing your information on this matter. It helps out a great deal.

**Comment by Hedwig7s** [comment]
BTW @KillzXGaming could you check out #507? Thanks

**Comment by Hedwig7s** [comment]
Oh BTW @KillzXGaming Splatoon 1 uses LunchPack right?

**Comment by Hedwig7s** [comment]
BTW @KillzXGaming You'll know more than me on this
What game engine does Splatoon 3 use, can you confirm Splatoon 1 uses LunchPack and what physics engine is in Splatoon 2 and 1?

**Comment by Volcan4436** [comment]
is it possible to only change the textures?

**Comment by napikuu** [comment]
> > Ah, I see. Fair enough then. Well, hopefully it can be done in the near future.
> 
> Actually it is possible with the [latest commit](https://ci.appveyor.com/api/buildjobs/vd8d70secwgdt4yw/artifacts/Toolbox-Latest.zip) but the scaling is broken

Hi i know this is a little late, but the link you sent isnt working for access reasons, do you have any other alternatives/new links? again, thank you sm

**Comment by DesperC** [comment]
as time goes on, more and more games will use v10 probably so as it becomes more of an issue im sure someone will figure out a way to crack v10
