### ISSUE TITLE
Importing models breaks weights

### ISSUE THREAD

**Issue by senscith** [KillzXGaming/Switch-Toolbox#51]
BOTW Wii U Version

Importing any file type besides .bfmdl leads the imported model being assigned a weight of 1 on the Root bone. Other weights still show as existing on child bones, however they seem to be overwritten by the Root and T-Pose in game.

**Comment by KillzXGaming** [comment]
Are you sure you're on the very latest build? That used to be a bug but I fixed it awhile ago.

**Comment by senscith** [comment]
Using Commit 01aca5cd3ec7da805eae72172ff14d076edf6f75 from 4/20/2019.

**Comment by KillzXGaming** [comment]
Try again on the new commit i made recently. Should fix the weight issues

**Comment by senscith** [comment]
They are. Thank you kindly.
