### ISSUE TITLE
Animations & Blender

### ISSUE THREAD

**Issue by ReedRMain** [KillzXGaming/Switch-Toolbox#514]
If I am exporting and importing animations in blender correctly, they are broken as of now.

**Comment by UntitledOutput** [comment]
1: export the model as dae and run it through [fbx converter](https://www.autodesk.com/developer-network/platform-technologies/fbx-converter-archives)
2: export the animation as smd
3: install this plugin for [blender](https://developer.valvesoftware.com/wiki/Blender_Source_Tools)
4: import the fbx then import the smd

**Comment by ReedRMain** [comment]
> 1: export the model as dae and run it through [fbx converter](https://www.autodesk.com/developer-network/platform-technologies/fbx-converter-archives) 2: export the animation as smd 3: install this plugin for [blender](https://developer.valvesoftware.com/wiki/Blender_Source_Tools) 4: import the fbx then import the smd

This is indeed the way to do it. (Also, thanks!)

**Comment by regulad** [comment]
This process worked for you, correct? I got the SMD to import into blender but the bones seem to be wrong and when imported onto it's own armaturethey have different names then when I add it to the fbx armature. The keyframes are there, but I can't seem to get them to do anything.

**Comment by regulad** [comment]
This process worked for you, correct? I got the SMD to import into blender but the bones seem to be wrong and when imported onto it's own armaturethey have different names then when I add it to the fbx armature. The keyframes are there, but I can't seem to get them to do anything. @ReedRMain @UntitledOutput

**Comment by ReedRMain** [comment]
> This process worked for you, correct? I got the SMD to import into blender but the bones seem to be wrong and when imported onto it's own armaturethey have different names then when I add it to the fbx armature. The keyframes are there, but I can't seem to get them to do anything. @ReedRMain @UntitledOutput

It's a bit buggy (unless its working as intended?), but for it to work for me I import the model into blender, touch nothing, and then immediately apply the .smd animation and it should work from there.

**Comment by JaimeShirazi** [comment]
Issue with this technique is that it doesn't seem to include scaling parameters, so any scaling in an animation is lost. This can be seen if you try exporting the item animations in Mario Kart.
