### ISSUE TITLE
Bone visibility animations corrupt on saving (Wii U). Prevents file being reopened.

### ISSUE THREAD

**Issue by vgisuruex** [KillzXGaming/Switch-Toolbox#53]
when i open up super mario 3d world's nokonoko.bfres and save it, it doesn't work anymore, and always gives me this error.
![image](https://user-images.githubusercontent.com/44421940/56804973-3142bc00-6845-11e9-8c3a-be52a4ef1215.png

nokonoko.bfres : https://ufile.io/a0wkgp6q

**Comment by KillzXGaming** [comment]
Fixed in https://github.com/KillzXGaming/Switch-Toolbox/commit/a41737031f0b3cbdd90b8710509a2eb49fbc9800
