### ISSUE TITLE
Crash when saving Wind Waker HD bfres models

### ISSUE THREAD

**Issue by SvenCakemann** [KillzXGaming/Switch-Toolbox#54]
I know WWHD models are a bit different than the ones that have been in focus for the majority of time, but I was wanting to share that as of today using the "save" buttons causes a crash when trying to using models from Wind Waker HD.

**Comment by KillzXGaming** [comment]
If you edit models for WWHD it is extremely limiting due to shaders. They should resave back fine. The materials should be untouched, kept the same amount, same mesh count, same names, and the same skin count. I'll probably have an option to inject a model keeping original data

**Comment by SvenCakemann** [comment]
I had attempted to do a recolor, basically, but some of the textures required (for example) listed having 11 mipmaps but when I tried inputting that amount in, it would replace it with 10; or if it called for 10, replace it with 9, etc. I'm assuming that has to with why it wasn't cooperating.

**Comment by KillzXGaming** [comment]
Textures can be different sizes. Do make sure you are on the latest, as i recently had fixed a few bfres saving bugs with WWHD

**Comment by SvenCakemann** [comment]
I just redownloaded it and updated it to be sure and I'm still getting the same issue on my end.  I'll just link a [pastebin ](https://pastebin.com/wdmntgBV) of the crashlog it's showing me, if that helps anything.

**Comment by KillzXGaming** [comment]
So you replace a texture, save and it gives an error? Which bfres does this happen on?

**Comment by SvenCakemann** [comment]
I just did a quick test since I had only been trying on one beforehand.

Pz.szs/bfres (Zelda), Tc.szs/bfres (Tingle) and Zl2.szs/bfres (Tetra) are what are currently giving me this error. I just tried doing the same thing with Link's model (Link.szs/bfres) and it doesn't give the error.

**Comment by KillzXGaming** [comment]
It appears to be an issue with texture pattern animations. They seem to load incorrectly with the bfres version

**Comment by KillzXGaming** [comment]
Fixed in https://github.com/KillzXGaming/Switch-Toolbox/commit/111f5c1a9ea87bf07de37e53aa1e5be89f539ec2
