### ISSUE TITLE
Pokemon Scarlet Violet Support

### ISSUE THREAD

**Issue by hYdos** [KillzXGaming/Switch-Toolbox#543]

**Comment by dinoking27** [comment]
i opened the download but it doesnt show anything on it I'm a beginner of switch toolbox on how to open the models and such

**Comment by dinoking27** [comment]
> > https://cdn.discordapp.com/attachments/930346248244969562/1041171314536362024/ob0002_00.trmdl Link to the model for the switch in game possibly
> 
> I see this info but how do you get to the files
> 
> { meshes: [ { filename: "chara_root" }, { filename: "origin" }, { filename: "loc_attach" }, { filename: "waist" }, { filename: "left_parts" }, { filename: "right_parts" }, { filename: "ljoycon_mesh" }, { filename: "rjoycon_mesh" }, { filename: "switch_mesh" } ], skeleton: { }, materials: [
> 
> ] }

it says its not supported btw
