### ISSUE TITLE
Importing DAE/FBX results in misaligned weights

### ISSUE THREAD

**Issue by senscith** [KillzXGaming/Switch-Toolbox#55]
Importing a DAE/FBX file results in misaligned weights. This happens simply by exporting as DAE then immediately importing it back into the Toolbox. Saving and exporting through MAX or Blender generates similar results.

![broken-weights](https://user-images.githubusercontent.com/49826109/58030822-41208980-7aed-11e9-8a1b-2203bb26cf44.jpg)

Also Imported DAE files in Blender seems to remove certain bones and mislabel remaining ones (ie "Head" bone is renamed as "Chin" bone in Blender). Max does not have this issue though does give warning about "null" bones. Exporting from Max as a DAE in ASCII imports fine into Blender.

**Comment by mg76Aniimations** [comment]
I have the same kind of issue. When exporting a model as fbx ( here, from blender 2.79) and importing it with the tool box, it cause the weights to be in the wrong order and result in stretching issues in game. The weights also get randomly placed on the model for an unknown reason.


Wrong weight order

![Capture d’écran (111)](https://user-images.githubusercontent.com/49676773/59285638-91af8080-8c6e-11e9-8623-9a4467e2f2c4.png)

Weights misplacement (  result after importing )

![Capture d’écran (110)](https://user-images.githubusercontent.com/49676773/59285680-a5f37d80-8c6e-11e9-8d3e-b18529d98139.png)

( how it should looks like)

![Capture d’écran (112)](https://user-images.githubusercontent.com/49676773/59285725-b86db700-8c6e-11e9-8b80-23b92497c91a.png) 

Result in game

![2019061117193200-F1C11A22FAEE3B82F21B330E1B786A39](https://user-images.githubusercontent.com/49676773/59285778-d3402b80-8c6e-11e9-8bbe-16d0d4f4554b.jpg)

**Comment by KillzXGaming** [comment]
I'll note this as fixed as it seems to be working fine and i've been using blender to export rigged models. If it still happens make sure to sent a sample dae or fbx of the model so it can be looked at.
