### ISSUE TITLE
How do I use this program???

### ISSUE THREAD

**Issue by woseugiafhndjn** [KillzXGaming/Switch-Toolbox#565]
I'm trying to use this program so I can use the green hill zone map for mario kart 8 in yuzu (https://gamebanana.com/mods/382728) and it says to replace the music I have to replace some files with this program. The instructions in the mod's readme are super weird and not very helpful, but I tried anyways. 
I setup the program like the guide told me and opened my legally dumped .nsp of mk8, and was able to find all the files it told me to find, but I can't edit them, delete them, or replace them. every option is greyed out. I'm super pissed because I can't find anyone else with the same problem, no help whatsoever, and the only instructions I have are nonsensical. 
![image](https://user-images.githubusercontent.com/123198887/213774667-8c4ab356-9225-4ec2-8e0e-0bae102e780b.png)
I didn't know where else to ask for help, and I know i'm probably not going to get a response for 10 years, but i figured i might as well try. please give me some sort of clue as to what the hell i'm actually supposed to do because i have no god damn idea.

**Comment by KillzXGaming** [comment]
You don't edit the nsp file, files go on the sd card directly or in the mod folder using yuzu. You can see this guides online to do this.

https://www.youtube.com/watch?v=_8gIJ8FnL1k

For using this program, I assume they are referring to BGM.bars editing as mentioned in this guide, which you dump and extract from the Audio\Static folder. https://gamebanana.com/tuts/15283 where you swap .bfstp files.
