### ISSUE TITLE
When using Toolbox on 4k monitor, the program ignores Window's zoom function.

### ISSUE THREAD

**Issue by ItzSka** [KillzXGaming/Switch-Toolbox#59]
When using Toolbox on 4k monitor, the program ignores Window's zoom function and makes the program font and buttons incredibly tiny. The program opens looking fine, but then changes the resolution of itself after importing a .bfres file. Not sure if this is something you can fix or not, but I'd be happy to test anything you come up with if you don't have a 4k monitor to test this on.

Before Importing a Bfres file:
![BeforeImportingBfres](https://user-images.githubusercontent.com/51541805/59163697-58daa480-8ad2-11e9-84de-79f0d0e6b5d6.jpg)

After Importing a Bfres file:
![AfterImportingBfres](https://user-images.githubusercontent.com/51541805/59163702-62640c80-8ad2-11e9-977f-3548501f5ac8.jpg)

**Comment by KillzXGaming** [comment]
Try the latest build.

**Comment by KillzXGaming** [comment]
Fixed by https://github.com/KillzXGaming/Switch-Toolbox/commit/d1adbc554762719f13c6aea1f33e3fa8f7331b53
