### ISSUE TITLE
Paper mario Color Splash files

### ISSUE THREAD

**Issue by WalterLeal** [KillzXGaming/Switch-Toolbox#594]
Please function to compress lz files of Paper Mario Color Splash for possible mods and translations.

**Comment by DanielSvoboda** [comment]
I added function to compress lz files of Paper Mario Color Splash, now it's available.
More details here: https://github.com/KillzXGaming/Switch-Toolbox/pull/604

**Comment by WalterLeal** [comment]
Thanks man. It's very important. 🙂
