### ISSUE TITLE
Error when exporting Metroid Prime Remastered models with UV Transforms applied

### ISSUE THREAD

**Issue by MetroidSky** [KillzXGaming/Switch-Toolbox#598]
When exporting a _.smdl_ model file from Metroid Prime Remastered with the export UV Transforms option checked, an _Object reference not set to an instance of of an object_ error pops up. I understand that the UVs for Metroid Prime Remastered are a work in progress, and this problem is quite difficult to fix. Without UV Transforms applied, the model's textures will wrapped on the model incorrectly.

**Comment by KillzXGaming** [comment]
That option will not affect that game anyways, only used for some games with bfres. Any material data like transform information is not supported.

**Comment by MetroidSky** [comment]
Alright. Thank you!
