### ISSUE TITLE
Request: Support for Mario Tennis Aces 0x20 compression CARCs/body.bin files (Deflate)?

### ISSUE THREAD

**Issue by LolHacksRule** [KillzXGaming/Switch-Toolbox#61]
Those files are only deflate compressed and can be decompressed with offzip but will the tool support these files to make datamining and future modding of the game easier?
[MTACARCs.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/3293592/MTACARCs.zip)

**Comment by KillzXGaming** [comment]
Alrigh, added in https://github.com/KillzXGaming/Switch-Toolbox/commit/8bbe51bb9cfb414950496b32f4b7af158ab72f56

**Comment by LolHacksRule** [comment]
The extension and compressed file inside is similarly used in Mario Tennis Ultra Smash, but with the 0x50 compression level, Simon time made a tool to decompress it, will that type file and/or 0x50'ed files entirely be also supported soon? Thanks so much.

**Comment by KillzXGaming** [comment]
Yes I have that planned.

**Comment by LolHacksRule** [comment]
Thanks so much for adding support for these files but there's a problem with this new feature of the program, I tried to open most of the 0x50 compressed files (excluding msg_kernel.dat) in the NARC/NPTL/BIN archives in both MTA and MTUS, but Switch Toolbox hangs forever and doesn't advance or crashes when loading any. Will this newly added feature be fixed soon to make dataminers like me have a better experience on looking at the game data?

**Comment by KillzXGaming** [comment]
Support isn't finished yet, although I ported all of the code, it doesn't seem to like how I handled some of the methods so it hangs, I need to look into a fix.

**Comment by LolHacksRule** [comment]
Thank you so much for trying to fix this the program hanging problem for 0x50 compression but when decompressing CBTEX files from NTEX (NARC) archives, CARC files from NARC archives (MTUS) and CBPTL files from NPTL (NARC) archives (MTUS), the program gives three error logs also BIN files from BIN files (NARC, MTUS) and CBVFX files from NPTL archives (MTA) hang the program. On the other hand aside of asking for fixes, will the Mario Tennis US/Aces specific file formats (NTEX, NPTL, BSNDC and BIN) be listed in the dropdown list for the Open file dialog? Thanks.

**Comment by LolHacksRule** [comment]
Not possible to open MTUS autodecompressed CARCs, body.bin files are fine. Will this be fixed?
[m_cameramode.narc.txt](https://github.com/KillzXGaming/Switch-Toolbox/files/3364026/m_cameramode.narc.txt)

**Comment by LolHacksRule** [comment]
As of the last updates, autodecompression of 0x50 compressed files is no longer working.

**Comment by LolHacksRule** [comment]
Hate having to rebump but it would be amazing for this to be fixed...
