### ISSUE TITLE
Can't open BOTW file because of TotK popup

### ISSUE THREAD

**Issue by H2714** [KillzXGaming/Switch-Toolbox#616]
I'm unable to open this edited BOTW texture file (others work fine), I get a popup reading "A game dump of TOTK is required to load this file. Please select the romfs folder path." and as I don't have TotK, I can get no further.
Tried remaking it but after saving I'm unable to open it again.
[Enemy_Lizalfos_Gold.Tex1.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/11611762/Enemy_Lizalfos_Gold.Tex1.zip)

Edit: Downgrading to version 1.0.2630 fixes the issue.

**Comment by ChaoticPumpkin** [comment]
+1. I was having this problem trying to load `/Model/Npc_Zora_Prince.Tex1.sbfres`. from BoTW. 
[Npc_Zora_Prince.Tex1.sbfres.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/11647982/Npc_Zora_Prince.Tex1.sbfres.zip)

**Comment by KillzXGaming** [comment]
Should work fine on latest
