### ISSUE TITLE
Exporting individual objects fails with error

### ISSUE THREAD

**Issue by SaberMage** [KillzXGaming/Switch-Toolbox#62]
This is different from the issue marked solved in the issue tracker, which applies to exporting "models." Exporting whole "models" works fine.

Instead, whenever attempting to export a singular "object" (child of a "model" in the tree), an error is thrown and the output file is corrupt.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/ae1f2ebb79a4cd392caea4a909ecbb22d4cc524b
