### ISSUE TITLE
Request: Mario and Rabbids MMB Support

### ISSUE THREAD

**Issue by ChaoticFusion40** [KillzXGaming/Switch-Toolbox#64]
I know this might be hard to do, but i wanted to ask to add support to the snowdrop .mmb format, with all the meshes, textures, etc applied to in good faith.

**Comment by ChaoticFusion40** [comment]
never mind, closing it.

**Comment by KillzXGaming** [comment]
I'll consider adding it in at some point, but i'm not sure how far i'll go.
