### ISSUE TITLE
MK8DX .dae exports crash Blender Cycles render

### ISSUE THREAD

**Issue by Takeshi-no-uta** [KillzXGaming/Switch-Toolbox#657]
After I import models into blender, then turn on GPU cycles (RTX3080 12GB), either of these error messages show up a few dozen samples in after a major freeze:

`Illegal address in CUDA queue copy_from_device (integrator_shade_surface integrator_sorted_paths_array prefix_sum)`
![image](https://github.com/KillzXGaming/Switch-Toolbox/assets/62028656/24ee9b22-dfc0-4bdb-a67f-70b17dc2fbea)

It happens with full tracks and simple kart bodies alike so from my POV I've no idea what it could be.

**Comment by steventylerseanherr** [comment]
test it with a non toolbox model on the same scale as a full mk8 map
i guarantee this is a you / your hardware / blender problem

**Comment by Platonic-DIVA** [comment]
This isn't a Toolbox issue, that is a Blender issue

**Comment by Takeshi-no-uta** [comment]
Yes. After some testing, it turns out that blender doesn't play well with the default OC mode for my GPU, weirdly. Thanks, anyway!
