### ISSUE TITLE
Invalid signature, expected 'DATA' but got 'AMTA'.

### ISSUE THREAD

**Issue by TheRealPepsi** [KillzXGaming/Switch-Toolbox#668]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Invalid signature, expected 'DATA' but got 'AMTA'.
   at BarsLib.IO.FileLoader.CheckSignature(String validSignature)
   at BarsLib.AMTADATA.BarsLib.IO.IFileData.Load(FileLoader loader)
   at BarsLib.IO.FileLoader.ReadResData[T]()
   at BarsLib.IO.FileLoader.Load[T](Boolean SeekOffset, UInt32 offset)
   at BarsLib.AMTA.BarsLib.IO.IFileData.Load(FileLoader loader)
   at BarsLib.IO.FileLoader.ReadResData[T]()
   at BarsLib.IO.FileLoader.Load[T](Boolean SeekOffset, UInt32 offset)
   at BarsLib.BARS.BarsLib.IO.IFileData.Load(FileLoader loader)
   at BarsLib.BARS..ctor(Stream stream)
   at FirstPlugin.BARS.Load(Stream stream) in E:\Switch-Toolbox-master\Switch-Toolbox-master\File_Format_Library\FileFormats\Audio\BARS\BARS.cs:line 240
   at Toolbox.Library.IO.STFileLoader.SetFileFormat(IFileFormat fileFormat, String FileName, Stream stream, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat FileCompression) in E:\Switch-Toolbox-master\Switch-Toolbox-master\Switch_Toolbox_Library\IO\STFileLoader.cs:line 240
   at Toolbox.Library.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, Int64 DecompressedSize, Int64 CompressedSize) in E:\Switch-Toolbox-master\Switch-Toolbox-master\Switch_Toolbox_Library\IO\STFileLoader.cs:line 222
   at Toolbox.Library.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, Int64 DecompressedSize, Int64 CompressedSize) in E:\Switch-Toolbox-master\Switch-Toolbox-master\Switch_Toolbox_Library\IO\STFileLoader.cs:line 203
   at Toolbox.Library.IO.STFileLoader.OpenFileFormat(String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, UInt32 DecompressedSize, UInt32 CompressedSize) in E:\Switch-Toolbox-master\Switch-Toolbox-master\Switch_Toolbox_Library\IO\STFileLoader.cs:line 165
   at Toolbox.MainForm.OpenFile(String FileName, Boolean InActiveEditor) in E:\Switch-Toolbox-master\Switch-Toolbox-master\Toolbox\MainForm.cs:line 281
   at Toolbox.MainForm.OpenFileSelect() in E:\Switch-Toolbox-master\Switch-Toolbox-master\Toolbox\MainForm.cs:line 252
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Toolbox
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/Toolbox.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9172.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Toolbox.Library
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/Toolbox.Library.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DirectXTexNetImpl
    Assembly Version: 1.0.0.3
    Win32 Version: 
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/x64/DirectXTexNetImpl.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
OpenTK
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/Lib/OpenTK.dll
----------------------------------------
SFGraphics
    Assembly Version: 1.0.6956.42501
    Win32 Version: 1.0.6956.42501
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/SFGraphics.DLL
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/Lib/OpenTK.GLControl.dll
----------------------------------------
Octokit
    Assembly Version: 0.31.0.0
    Win32 Version: 0.31.0.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/Octokit.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
FirstPlugin.Plg
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/FirstPlugin.Plg.DLL
----------------------------------------
GL_EditorFramework
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/GL_EditorFramework.DLL
----------------------------------------
FlatBuffers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/FlatBuffers.DLL
----------------------------------------
Syroot.NintenTools.NSW.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/Syroot.NintenTools.NSW.Bfres.DLL
----------------------------------------
Syroot.Maths
    Assembly Version: 1.5.3.0
    Win32 Version: 1.5.3.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/Syroot.Maths.DLL
----------------------------------------
Syroot.NintenTools.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/Syroot.NintenTools.Bfres.DLL
----------------------------------------
Syroot.BinaryData
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/Lib/Syroot.BinaryData.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.1.22727
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/Newtonsoft.Json.DLL
----------------------------------------
Syroot.NintenTools.NSW.Bntx
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/Syroot.NintenTools.NSW.Bntx.DLL
----------------------------------------
SPICA
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/SPICA.DLL
----------------------------------------
ZeldaLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/ZeldaLib.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ZstdNet
    Assembly Version: 1.3.3.0
    Win32 Version: 1.3.3.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/ZstdNet.DLL
----------------------------------------
BarsLibrary
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Switch-Toolbox-master/Switch-Toolbox-master/Toolbox/bin/Release/BarsLibrary.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by TheRealPepsi** [comment]
(I tried the release build and building from the latest source myself, neither working)

**Comment by KillzXGaming** [comment]
Same issue as https://github.com/KillzXGaming/Switch-Toolbox/issues/208 . V5 bars is not supported
