### ISSUE TITLE
New update rendered useless this program

### ISSUE THREAD

**Issue by Machow8** [KillzXGaming/Switch-Toolbox#71]
Hello,

Today an update appeared, clicked to download and when finished, program is totally useless now.

I'm unable to open it without showing the following error message:

"Wasn't possible to load file or assembly 'Open TK, Version=3.0.1.0, Culture=neutral, PublicKey Token=bad199fe84eb3df4' or one of it' dependencies. System couldn't find specifyed path."

I'm also unable to open any file with/in it.

Program's version: de72038

I hope this is fixed very soon, so, we're able to continue using this app.

**Comment by KillzXGaming** [comment]
Try redownloading from github, right click zip, properties and check unblock ,Then extract to a clean folder.

**Comment by Machow8** [comment]
I did that and worked!

Thanks!
