### ISSUE TITLE
Weird Changes: Request to remove those weird limitations

### ISSUE THREAD

**Issue by Machow8** [KillzXGaming/Switch-Toolbox#73]
Hello,

I noticed that after redownloading this your program i noticed some weird changes in it:

1] Unable to take screenshots with your program's window when it is active/selected;

2] Unable to drag and drop the file i wanna open in your app to it' screen and your program detect that and automatically open it: before, for example, if i drag and drop M1_Model.pack to/into Switch Toolbox' screen, it detect that act and automatically opened that file ready for use. In that new version i can't do this.

In version i had which got turned unusable i didn't face the above issues, so, please, remove those weird limitations when possible.

Thanks!

**Comment by GRAnimated** [comment]
You ran it as administrator. Don’t do that next time.

**Comment by Machow8** [comment]
Oh, i didn't know that!

Doing what you described made it work.

Thanks!
