### ISSUE TITLE
Suggested Extension Changes: MSBT and SARC

### ISSUE THREAD

**Issue by LolHacksRule** [KillzXGaming/Switch-Toolbox#75]
MSBT files are not titled MeSsage Binary TexT, its titled Message Studio Binary, MsgStd in the header relates to Message Studio, the internal tool Nintendo devs (translators) use to make these files.

If you are unsure, look up Nintendo Message Studio on Google more info, the mobile games, Mario Run via (libms.so and/or the il2cpp Unity code), Miitomo (libcocos2dx.so), ACPC (locations, code) and MKT (libms.so, LMS) also mention this file as the extension above.

**Comment by CosmicDreamsOfCode** [comment]
What does the T in MSBT mean then?
Table?

**Comment by LolHacksRule** [comment]
I forget SARC, being Sorted ARChive from Karameru's file naming.

T on the other hand is the one I'm not sure about, maybe it could be Table.

**Comment by aboood40091** [comment]
SARC stands for Sharc Archive. No idea what Sharc means though.

**Comment by LolHacksRule** [comment]
@CosmicDreamsOfCode Turns out its not Table, its Text, MSBTs aren't tabular, they are made as plaintext XML files (MSTXT, not MSTBL, thus proving they aren't tabular) in the internal program, then converted with it to the binary format ready for public games we know.

**Comment by LolHacksRule** [comment]
The new name of SARC is Sead (hashed) Archived ResourceP

**Comment by aboood40091** [comment]
*Abood 🤔
It was just a guess. People should just leave it as Sharc imo because that's what sead (Nintendo's standard library) calls it.
