### ISSUE TITLE
BNVIB file from Mario Tennis Aces vibs.narc fails to decompress (BASE ONLY?)

### ISSUE THREAD

**Issue by LolHacksRule** [KillzXGaming/Switch-Toolbox#77]
The file **Audio_Bam_1.bnvib** from **vibs.narc** in the game's files is pre-decompressed to completely empty in Switch Toolbox, every other file is decompressed correctly, will this be fixed? Here's the file that exported fine from Aluigi's MTA NARC decompression script (http://aluigi.org/bms/mario_tennis_narc.bms) and RTB's decompression script (https://mega.nz/#!i5h03IRB!s7BYtPqmW9R4Vww1u_En-e24qbSXsnIwiCqgbwSASjU). [Audio_Bam_1.bnvib](https://github.com/KillzXGaming/Switch-Toolbox/files/3347957/Audio_Bam_1.bnvib.txt)

Oh and here's the file containing them.
[vibs.narc](https://github.com/KillzXGaming/Switch-Toolbox/files/3347947/vibs.narc.txt)

**Comment by KillzXGaming** [comment]
From what i can tell, it's failing to decompress with zlib, not sure why though.

**Comment by LolHacksRule** [comment]
Oh, its not compressed by ZLib, its compressed by GZip.

**Comment by KillzXGaming** [comment]
But it doesn't have the gzip magic, and other files work fine

**Comment by LolHacksRule** [comment]
No, it does, I compressed the extracted file with GZip on my own to check and I saw similar data when comparing its hexes with the hexes of the compressed file from the game.
[Audio_Bam_1_mycomp.bnvib.txt](https://github.com/KillzXGaming/Switch-Toolbox/files/3364308/Audio_Bam_1_mycomp.bnvib.txt)

![image](https://user-images.githubusercontent.com/30186527/60750154-1e411c00-9f59-11e9-9d5d-553e7b6eca0c.png)

**Comment by LolHacksRule** [comment]
This still isn't fixed. Please respond.

**Comment by KillzXGaming** [comment]
If i had a fix for this, it would've been fixed already. I have already looked into this, the c# deflatestream simply doesn't work with that particular file.

**Comment by KillzXGaming** [comment]
These should be fixed
