### ISSUE TITLE
Request: SGARC.CMP support (Mii Maker, Wii U)

### ISSUE THREAD

**Issue by LolHacksRule** [KillzXGaming/Switch-Toolbox#78]
Switch Toolbox cannot decompress these files, Aluigi made this script (http://aluigi.org/bms/mii_maker.bms) to decompress these. They are zlib compressed files, outputting a SA01 compressed file with the data.
[WIIU_MiiMaker.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/3347972/WIIU_MiiMaker.zip)

**Comment by samer-81** [comment]
> Switch Toolbox cannot decompress these files, Aluigi made this script (http://aluigi.org/bms/mii_maker.bms) to decompress these. They are zlib compressed files, outputting a SA01 compressed file with the data. [WIIU_MiiMaker.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/3347972/WIIU_MiiMaker.zip)

Aluigi script can indeed decompress the files, but wasn't able to reimporting the file, any idea how to recompress the file back after making changes ?
