### ISSUE TITLE
Request: Support for Mario Kart 8 BIN files? 

### ISSUE THREAD

**Issue by LolHacksRule** [KillzXGaming/Switch-Toolbox#79]
Will support for Mario Kart 8's unique BIN files in the Mush directory be supported soon? This program (http://mk8.tockdom.com/wiki/BIN_Editor) can open some and here's a documentation on the format of them. http://mk8.tockdom.com/wiki/BIN_(File_Format)

**Comment by KillzXGaming** [comment]
I was planning on a visual parts.bin editor, but due to how complex it is, and there being so many parameters i decided to scrap the idea. I do not plan to support any of other bin formats as i don't see any reason to, the bin editors seem to be perfectly fine for what the other types do.

**Comment by LolHacksRule** [comment]
Oh ok then.
