### ISSUE TITLE
Unable to batch export textures from some SMM1 folders

### ISSUE THREAD

**Issue by El-Vallo** [KillzXGaming/Switch-Toolbox#83]
Hello,

Switch Toolbox is actually unable to batch export textures from following SMM1 files:

Base game: Pack folder;

1.47 update: Bossnfp and Pack folders.

Will be awesome when those are fixed.

Note: i'm trying to extract USA region files (i don't know if there are differences between region files of same game).

Once again, thanks for your great support!

**Comment by KillzXGaming** [comment]
I think it's fixed now, i don't have the update but be sure to try the latest

**Comment by El-Vallo** [comment]
It Works now.

Thanks!
