### ISSUE TITLE
Pressing "no" after choosing to deleting a model deletes contents of model anyway

### ISSUE THREAD

**Issue by malistaticy** [KillzXGaming/Switch-Toolbox#84]
After right clicking a model in the Models browser and selecting delete, and then pressing "No", the model will remain as expected, but the objects and materials and skeleton within it will get deleted anyway.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/7bbd06701f802c058fc410ad2b5257cabc02f773
