### ISSUE TITLE
Super Mario Maker 2 .ptcl files fail to save properly (version 0x25)

### ISSUE THREAD

**Issue by SuperOkazaki** [KillzXGaming/Switch-Toolbox#86]
While attempting to save a .ptcl file from Super Mario Maker 2 (specifically RomFS://Effect/Static.Nin_NX_NVN.szs/Particle.Nin_NX_NVN.ptcl) the software has a generic unhandled exception and crashes.

**Comment by KillzXGaming** [comment]
Now it won't crash on save, but i believe there's some version differences, so it'll still fail to work in game atm

**Comment by SuperOkazaki** [comment]
Thank you for the prompt reply! When I get off work I’ll try editing it and seeing the results even though you said it will crash. Looking forward to fully editing the files for in-game.

**Comment by KillzXGaming** [comment]
Works now!
