### ISSUE TITLE
Blender imports DAE without any weights and bones at all

### ISSUE THREAD

**Issue by Optimus97100** [KillzXGaming/Switch-Toolbox#90]
In previous versions of Toolbox, when I exported a Splatoon 2 model in DAE format and imported it into Blender, it used to have proper skeleton (armature) and all vertex weights.
![image](https://user-images.githubusercontent.com/53050984/61468299-b2fa3f80-a985-11e9-8186-a02fed5cfb8a.png)
Now if I export a DAE with the current version, there's none of them. Only **weightless mesh** and a bunch of **empties** with supposed bones' hierarchy and names.
![image](https://user-images.githubusercontent.com/53050984/61468154-7deded00-a985-11e9-8b8c-ed976a5df521.png)

**Comment by KillzXGaming** [comment]
Should be fixed now.

**Comment by Optimus97100** [comment]
Now it gives me an "unhandled exception" error, right after I start exporting. I don't know what causes it
![image](https://user-images.githubusercontent.com/53050984/61480956-bbf80a80-a99f-11e9-98b8-67c061ecdd19.png)

**Comment by Optimus97100** [comment]
Now it gives me an "unhandled exception" error, right after I start exporting. I don't know what causes it
![image](https://user-images.githubusercontent.com/53050984/61480956-bbf80a80-a99f-11e9-98b8-67c061ecdd19.png)

**Comment by KillzXGaming** [comment]
You'll need to redownload the tool and put it in a clean folder, as it conflicts with an older version

**Comment by Optimus97100** [comment]
I did. "Releases" => "Experimental Release". Several times, I swear.

**Comment by KillzXGaming** [comment]
Can you try removing assimp.dll?

**Comment by Optimus97100** [comment]
Still an error. Now it can't find assimp.dll
![2019-07-18_21-19-34](https://user-images.githubusercontent.com/53050984/61481835-c4e9db80-a9a1-11e9-8b11-d6a232d9f54d.png)

**Comment by KillzXGaming** [comment]
Try the newest one. I think it'll work now

**Comment by Optimus97100** [comment]
Yes! It works, now, complete with armatures. Thank you
