### ISSUE TITLE
Format 8 unorm gives incorrect weights. 

### ISSUE THREAD

**Issue by GingerAvalanche** [KillzXGaming/Switch-Toolbox#91]
Whenever I import a model to a bfres (with any method: dae, csv, obj, fbx) the model appears in the viewer just fine, but when I load it into BotW, most of the verts have lost their weights.

I'm able to recreate what I see in-game in the model viewer if I change the Blend Weight vertex buffer format to `Format_8_UNorm`.

It should be noted that if I use the old BFRES_Vertex python script on a csv, the weights are viewed properly by both toolbox and the game.

What it looks like in the viewer (Weight buffer format is `Format_8_8_8_8_UNorm`)
![Screenshot (157)](https://user-images.githubusercontent.com/32864080/61700706-cee94280-acf1-11e9-83d1-9ad464b008b3.png)

What it looks like in-game
![Screenshot (154)](https://user-images.githubusercontent.com/32864080/61700782-f213f200-acf1-11e9-8e61-b982bcfbf34c.png)

What it looks like in the viewer with Format_8_UNorm
![Screenshot (158)](https://user-images.githubusercontent.com/32864080/61700933-27b8db00-acf2-11e9-89ec-cae0bfe4e758.png)

**Comment by GingerAvalanche** [comment]
Upon testing different things involving #92 , this seems to be a product of the fact that I was converting my weights to 8-bit UNorms.

Given that my Cemu crashes if I ever use any weight buffer size larger than 8-bit (it's unknown if this crash affects others as well) this means that I have to first import a model using toolbox to set the number of vertices on each model, then import the vert buffer data using BFRES_Vertex.

I've finally managed to fix all of my weighting issues regarding the model I was trying to import, and I've gotten it in-game using the method described in the previous paragraph, so I feel relatively confident that this issue, unlike 92, is not user error.

**Comment by KillzXGaming** [comment]
I should note, for CSV I have made a small work around trying to fix it. I know the Python script works, so I tried setting the weights in the same way before they get encoding. It's not exactly the same results for some reason, but it seems to be somewhat improved.
