### ISSUE TITLE
Vertex Buffer Import Format Bug

### ISSUE THREAD

**Issue by GingerAvalanche** [KillzXGaming/Switch-Toolbox#92]
When replacing a mesh, the advanced settings tab has a bunch of dropdowns to allow you to choose formats.

If you choose Format_32_32_32_32_Single for Format (Weights), it actually uses Format_32_32_32_Single. There may also be other discrepancies I haven't noticed.

**Comment by KillzXGaming** [comment]
Depending on the amount of weights/skinning is used, it may decrease it to save on space. ie 3 floats for skinning of 3, or 1 float for single weights.

**Comment by GingerAvalanche** [comment]
It does this even at a loss of data, though. When I choose for the weights to be 4 floats, it imports them with 3 floats and wipes out all my weight arrays of length 4+.

**Comment by KillzXGaming** [comment]
Aslong as the skin count is 4 (your model has to have atleast one vertex with 4 weights) then it should be set to 4 values.The tool automatically chooses float with 4 32 values, as it's the best working format (8 unorm has odd inaccuracies atm) and it lowers it depending on how many bones are rigged to a vertex.

**Comment by GingerAvalanche** [comment]
It makes sense that that’s what is supposed to happen.

My report is that when I choose to use the 4 float buffer format, the tool treats it as if I chose the 3 float buffer format and drops the 4th float from all vertices, and in the resulting vertex buffer list it shows the format of the weights as Format_32_32_32_Single - 3 floats. Viewing that buffer only shows 3 columns, and thus 3 weights per vertex.

The tool does, as you say, default to the 4 float format in the dropdown when importing. However, it doesn’t actually use that format for the import.

**Comment by KillzXGaming** [comment]
When you select your mesh, what is the skin count shown in the editor?

**Comment by GingerAvalanche** [comment]
I will need to check when I get home. I’ll be at work for another several hours.

**Comment by GingerAvalanche** [comment]
.....Huh. It's displaying a skin count of 3. The Blend Index buffer also has a fully empty fourth column despite its 4-value format, so it's just not importing the 4th value of each array. I 100% definitely have a fourth value for a lot of verts in the csv I'm loading from, though.

Screenshot evidence:
![Screenshot (160)](https://user-images.githubusercontent.com/32864080/61760738-5cc03e80-ad81-11e9-8be0-1dee179ecddd.png)

**Comment by GingerAvalanche** [comment]
Nevermind, I figured it out. I had Keep Original Skin Count checked. The original model I was editing had a skin count of 3. I'm a doofus, it was user error.
