### ISSUE TITLE
Changing a texture wrap to some types causes an unhandled exception

### ISSUE THREAD

**Issue by roket333** [KillzXGaming/Switch-Toolbox#97]
If you change a material's texture wrap method to "Mirror Once Border", "Clamp Border", "Clamp Half Border", and "Mirror Once Half Border", the program will spit out an Unhandled Exception message box, of which the error is "The given key was not present in the dictionary"
Additionally, the viewport will turn solid white with a red X
Oddly, the exception does not happen if the texture you're modifying the wrap of is not loaded

**Comment by KillzXGaming** [comment]
Alright fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/8b2a89c93c4e45589e35af2c37ab2fe45e018122
