### ISSUE TITLE
.DAE does not export or import mesh names

### ISSUE THREAD

**Issue by roket333** [KillzXGaming/Switch-Toolbox#99]
Pretty self-explanatory, Switch Toolbox does not export mesh names, nor import them, but only for .DAE

**Comment by KillzXGaming** [comment]
But it does export and import mesh names perfectly fine and i've tested blender, max, maya and noesis daes. I'm not quite sure if i understand, are you using 0.8 or the latest?

**Comment by roket333** [comment]
It must be some sort of issue with C4D and it's DAEs then, and i'm using the latest version
[Npc_Zora_Prince.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/3448454/Npc_Zora_Prince.zip)
here is a DAE from C4D, importing it into the current STB version should rename all meshes to "ID" with a random number

**Comment by KillzXGaming** [comment]
Ah yup it is a C4D issue, the way nodes are handled it seems the current library doesn't detect it. Since i'm using an external library, atm i can't quite fix it but i have my own that is planned to fix alot of issues.

**Comment by KillzXGaming** [comment]
Should be fixed now
